"""
React组件生成器 Skill
====================
生成React组件（Hooks + TypeScript）
"""

from pathlib import Path
from typing import List, Dict, Optional


class ReactComponentGenerator:
    """React组件生成器"""

    def __init__(self, output_dir: str = ".", typescript: bool = True):
        self.output_dir = Path(output_dir)
        self.typescript = typescript

    def generate(
        self,
        component_name: str,
        props: Optional[List[Dict]] = None,
        hooks: Optional[List[str]] = None,
        features: Optional[List[str]] = None
    ) -> Dict[str, str]:
        """
        生成React组件

        Args:
            component_name: 组件名称（PascalCase）
            props: 属性定义列表
            hooks: 使用的hooks列表
            features: 特性列表

        Returns:
            生成的代码字典
        """
        props = props or []
        hooks = hooks or ['useState']
        features = features or []

        results = {}

        # 生成组件
        results['component'] = self._generate_component(component_name, props, hooks, features)

        # 生成类型定义
        if self.typescript:
            results['types'] = self._generate_types(component_name, props)

        # 生成测试
        results['test'] = self._generate_test(component_name, props)

        # 生成样式
        if 'styled' in features:
            results['styles'] = self._generate_styled(component_name)
        else:
            results['css'] = self._generate_css(component_name)

        return results

    def _generate_component(
        self,
        name: str,
        props: List[Dict],
        hooks: List[str],
        features: List[str]
    ) -> str:
        """生成React组件代码"""
        ext = 'tsx' if self.typescript else 'jsx'

        # 导入语句
        imports = ["import React"]
        hook_imports = []
        for hook in hooks:
            if hook in ['useState', 'useEffect', 'useCallback', 'useMemo', 'useRef', 'useContext']:
                hook_imports.append(hook)
        if hook_imports:
            imports[0] = f"import React, {{ {', '.join(hook_imports)} }} from 'react'"

        if 'styled' in features:
            imports.append("import styled from 'styled-components'")
        else:
            imports.append(f"import './{name}.css'")

        if self.typescript:
            imports.append(f"import type {{ {name}Props }} from './{name}.types'")

        # Props解构
        props_destructure = ""
        if props:
            prop_names = [p['name'] for p in props]
            props_destructure = f"{{ {', '.join(prop_names)} }}"

        # Hooks使用
        hooks_code = []
        if 'useState' in hooks:
            hooks_code.append("  const [state, setState] = useState(null)")
        if 'useEffect' in hooks:
            hooks_code.append("""  useEffect(() => {
    // 副作用逻辑
    return () => {
      // 清理函数
    }
  }, [])""")
        if 'useCallback' in hooks:
            hooks_code.append("""  const handleClick = useCallback(() => {
    // 处理点击
  }, [])""")

        hooks_str = "\n\n".join(hooks_code) if hooks_code else ""

        # Loading状态
        loading_code = ""
        if 'loading' in features:
            loading_code = """
  if (loading) {
    return <div className="loading">Loading...</div>
  }
"""

        # 组件类型
        type_annotation = f": React.FC<{name}Props>" if self.typescript else ""

        return f'''{chr(10).join(imports)}

/**
 * {name} 组件
 * Generated by Leo React Component Generator
 */
const {name}{type_annotation} = ({props_destructure}) => {{
{hooks_str}
{loading_code}
  return (
    <div className="{self._to_kebab_case(name)}">
      {{/* 组件内容 */}}
    </div>
  )
}}

export default {name}
'''

    def _generate_types(self, name: str, props: List[Dict]) -> str:
        """生成TypeScript类型定义"""
        lines = [f"// {name} 类型定义", ""]

        lines.append(f"export interface {name}Props {{")
        for prop in props:
            pname = prop['name']
            ptype = self._map_ts_type(prop.get('type', 'string'))
            required = prop.get('required', False)
            optional = "" if required else "?"
            desc = prop.get('description', '')
            if desc:
                lines.append(f"  /** {desc} */")
            lines.append(f"  {pname}{optional}: {ptype}")
        lines.append("}")

        return "\n".join(lines)

    def _generate_test(self, name: str, props: List[Dict]) -> str:
        """生成测试文件"""
        props_mock = "{"
        for prop in props:
            pname = prop['name']
            ptype = prop.get('type', 'string')
            if ptype == 'string':
                props_mock += f"\n      {pname}: 'test',"
            elif ptype == 'number':
                props_mock += f"\n      {pname}: 1,"
            elif ptype == 'boolean':
                props_mock += f"\n      {pname}: true,"
            else:
                props_mock += f"\n      {pname}: {{}},"
        props_mock += "\n    }" if props else "{}"

        return f'''import {{ render, screen }} from '@testing-library/react'
import {{ describe, it, expect }} from 'vitest'
import {name} from './{name}'

describe('{name}', () => {{
  it('renders without crashing', () => {{
    render(<{name} {{...{props_mock}}} />)
    expect(screen.getByRole('generic')).toBeInTheDocument()
  }})

  it('matches snapshot', () => {{
    const {{ container }} = render(<{name} {{...{props_mock}}} />)
    expect(container).toMatchSnapshot()
  }})
}})
'''

    def _generate_css(self, name: str) -> str:
        """生成CSS文件"""
        kebab = self._to_kebab_case(name)
        return f'''.{kebab} {{
  /* 组件样式 */
}}

.{kebab} .loading {{
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100px;
}}
'''

    def _generate_styled(self, name: str) -> str:
        """生成styled-components"""
        return f'''import styled from 'styled-components'

export const {name}Wrapper = styled.div`
  /* 组件样式 */
`

export const LoadingWrapper = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100px;
`
'''

    def _map_ts_type(self, ptype: str) -> str:
        """映射TypeScript类型"""
        type_map = {
            'string': 'string',
            'number': 'number',
            'boolean': 'boolean',
            'array': 'any[]',
            'object': 'Record<string, any>',
            'function': '(...args: any[]) => void',
            'node': 'React.ReactNode',
            'element': 'React.ReactElement'
        }
        return type_map.get(ptype.lower(), 'any')

    def _to_kebab_case(self, name: str) -> str:
        """转换为kebab-case"""
        import re
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1-\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1-\2', s1).lower()

    def save_files(self, component_name: str, results: Dict[str, str]) -> Dict[str, Path]:
        """保存生成的文件"""
        saved = {}
        comp_dir = self.output_dir / 'components' / component_name
        comp_dir.mkdir(parents=True, exist_ok=True)

        ext = 'tsx' if self.typescript else 'jsx'

        # 组件文件
        comp_path = comp_dir / f'{component_name}.{ext}'
        comp_path.write_text(results['component'], encoding='utf-8')
        saved['component'] = comp_path

        # 类型文件
        if 'types' in results:
            types_path = comp_dir / f'{component_name}.types.ts'
            types_path.write_text(results['types'], encoding='utf-8')
            saved['types'] = types_path

        # 测试文件
        test_path = comp_dir / f'{component_name}.test.{ext}'
        test_path.write_text(results['test'], encoding='utf-8')
        saved['test'] = test_path

        # 样式文件
        if 'css' in results:
            css_path = comp_dir / f'{component_name}.css'
            css_path.write_text(results['css'], encoding='utf-8')
            saved['css'] = css_path
        elif 'styles' in results:
            styles_path = comp_dir / f'{component_name}.styles.ts'
            styles_path.write_text(results['styles'], encoding='utf-8')
            saved['styles'] = styles_path

        # 导出文件
        index_content = f"export {{ default }} from './{component_name}'\n"
        if 'types' in results:
            index_content += f"export * from './{component_name}.types'\n"
        index_path = comp_dir / 'index.ts'
        index_path.write_text(index_content, encoding='utf-8')
        saved['index'] = index_path

        return saved


def main():
    """示例用法"""
    generator = ReactComponentGenerator(output_dir="./output", typescript=True)

    results = generator.generate(
        component_name='UserCard',
        props=[
            {'name': 'name', 'type': 'string', 'required': True, 'description': '用户名'},
            {'name': 'avatar', 'type': 'string', 'description': '头像URL'},
            {'name': 'onClick', 'type': 'function', 'description': '点击回调'}
        ],
        hooks=['useState', 'useEffect', 'useCallback'],
        features=['loading']
    )

    saved = generator.save_files('UserCard', results)
    print("生成完成！")
    for name, path in saved.items():
        print(f"  {name}: {path}")


if __name__ == '__main__':
    main()
