"""
deployment_script_generator_skill

部署脚本生成技能 - 生成部署、回滚和健康检查脚本。
支持 Docker、PM2、Systemd 三种部署方式。
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from leo_skills.core.base_executor import BaseExecutor


class DeploymentScriptGenerator(BaseExecutor):
    """部署脚本生成器。

    根据服务器信息和部署类型，自动生成：
    - 部署脚本 (deploy.sh)
    - 回滚脚本 (rollback.sh)
    - 健康检查脚本 (health_check.sh)

    支持的部署类型：docker / pm2 / systemd
    """

    def __init__(self, output_dir: str = ".") -> None:
        self.name = "deployment_script_generator_skill"
        self.output_dir = Path(output_dir)

    # ------------------------------------------------------------------
    # BaseExecutor 接口
    # ------------------------------------------------------------------

    def execute(
        self,
        action: str = "generate",
        context: Optional[Dict[str, Any]] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """执行技能主入口。

        Args:
            action: 执行动作，支持 "generate" (默认)
            context: 上下文参数
            **kwargs: 额外参数，与 context 合并

        context / kwargs 支持的参数：
            server_info (dict): 服务器信息，包含 host / user / registry / port / health_path 等
            deploy_type (str): 部署类型，docker / pm2 / systemd，默认 docker
            project_name (str): 项目名称，默认 "app"
        """
        params: Dict[str, Any] = dict(context or {})
        params.update(kwargs)

        server_info = params.get("server_info", {
            "host": "localhost",
            "user": "root",
            "registry": "docker.io",
            "port": 80,
            "health_path": "/health",
        })
        deploy_type = params.get("deploy_type", "docker")
        project_name = params.get("project_name", "app")

        scripts = self.generate(
            server_info=server_info,
            deploy_type=deploy_type,
            project_name=project_name,
        )

        return {
            "status": "success",
            "action": action,
            "deploy_type": deploy_type,
            "project_name": project_name,
            "scripts": list(scripts.keys()),
            "data": scripts,
        }

    # ------------------------------------------------------------------
    # 核心生成方法
    # ------------------------------------------------------------------

    def generate(
        self,
        server_info: Dict[str, Any],
        deploy_type: str = "docker",
        project_name: str = "app",
    ) -> Dict[str, str]:
        """生成部署脚本集合。

        Args:
            server_info: 服务器信息 (host / user / registry / port / health_path)
            deploy_type: 部署类型 (docker / pm2 / systemd)
            project_name: 项目名称

        Returns:
            包含 deploy / rollback / health_check 三个脚本内容的字典
        """
        generators = {
            "docker": self._generate_docker_deploy,
            "pm2": self._generate_pm2_deploy,
            "systemd": self._generate_systemd_deploy,
        }

        generator = generators.get(deploy_type, self._generate_docker_deploy)
        deploy_script, rollback_script = generator(server_info, project_name)

        return {
            "deploy": deploy_script,
            "rollback": rollback_script,
            "health_check": self._generate_health_check(server_info, project_name),
        }

    # ------------------------------------------------------------------
    # Docker 部署
    # ------------------------------------------------------------------

    def _generate_docker_deploy(
        self, server: Dict[str, Any], name: str
    ) -> Tuple[str, str]:
        """生成 Docker 部署 + 回滚脚本。"""
        host = server.get("host", "localhost")
        user = server.get("user", "root")
        registry = server.get("registry", "docker.io")

        deploy = f'''#!/bin/bash
# Docker 部署脚本
# Generated by Leo Deployment Script Generator

set -e

# 配置
APP_NAME="{name}"
SERVER="{user}@{host}"
REGISTRY="{registry}"
IMAGE="$REGISTRY/$APP_NAME:${{TAG:-latest}}"

echo "[LAUNCH] 开始部署 $APP_NAME"

# 1. 构建镜像
echo "构建 Docker 镜像..."
docker build -t $IMAGE .

# 2. 推送镜像
echo "推送镜像到仓库..."
docker push $IMAGE

# 3. 远程部署
echo "远程部署..."
ssh $SERVER << 'ENDSSH'
    cd /opt/$APP_NAME

    # 备份当前版本
    docker tag $IMAGE $IMAGE.backup 2>/dev/null || true

    # 拉取新镜像
    docker pull $IMAGE

    # 停止旧容器
    docker-compose down

    # 启动新容器
    docker-compose up -d

    # 清理旧镜像
    docker image prune -f
ENDSSH

echo "[SUCCESS] 部署完成!"
'''

        rollback = f'''#!/bin/bash
# Docker 回滚脚本
# Generated by Leo Deployment Script Generator

set -e

APP_NAME="{name}"
SERVER="{user}@{host}"
REGISTRY="{registry}"
IMAGE="$REGISTRY/$APP_NAME"

echo "开始回滚 $APP_NAME"

ssh $SERVER << 'ENDSSH'
    cd /opt/$APP_NAME

    # 停止当前版本
    docker-compose down

    # 恢复备份版本
    docker tag $IMAGE.backup $IMAGE:latest

    # 启动备份版本
    docker-compose up -d
ENDSSH

echo "[SUCCESS] 回滚完成!"
'''

        return deploy, rollback

    # ------------------------------------------------------------------
    # PM2 部署
    # ------------------------------------------------------------------

    def _generate_pm2_deploy(
        self, server: Dict[str, Any], name: str
    ) -> Tuple[str, str]:
        """生成 PM2 部署 + 回滚脚本。"""
        host = server.get("host", "localhost")
        user = server.get("user", "root")
        path = server.get("path", f"/opt/{name}")

        deploy = f'''#!/bin/bash
# PM2 部署脚本
# Generated by Leo Deployment Script Generator

set -e

APP_NAME="{name}"
SERVER="{user}@{host}"
DEPLOY_PATH="{path}"

echo "[LAUNCH] 开始部署 $APP_NAME"

# 同步代码
rsync -avz --exclude 'node_modules' --exclude '.git' ./ $SERVER:$DEPLOY_PATH/

# 远程安装依赖和重启
ssh $SERVER << 'ENDSSH'
    cd $DEPLOY_PATH
    npm install --production
    pm2 reload ecosystem.config.js --env production
ENDSSH

echo "[SUCCESS] 部署完成!"
'''

        rollback = f'''#!/bin/bash
# PM2 回滚脚本

APP_NAME="{name}"
SERVER="{user}@{host}"

ssh $SERVER "cd {path} && git checkout HEAD~1 && pm2 reload all"

echo "[SUCCESS] 回滚完成!"
'''

        return deploy, rollback

    # ------------------------------------------------------------------
    # Systemd 部署
    # ------------------------------------------------------------------

    def _generate_systemd_deploy(
        self, server: Dict[str, Any], name: str
    ) -> Tuple[str, str]:
        """生成 Systemd 部署 + 回滚脚本。"""
        host = server.get("host", "localhost")
        user = server.get("user", "root")

        deploy = f'''#!/bin/bash
# Systemd 部署脚本
# Generated by Leo Deployment Script Generator

set -e

APP_NAME="{name}"
SERVER="{user}@{host}"

echo "[LAUNCH] 开始部署 $APP_NAME"

# 同步代码
rsync -avz ./ $SERVER:/opt/$APP_NAME/

# 远程重启服务
ssh $SERVER << 'ENDSSH'
    cd /opt/$APP_NAME
    pip install -r requirements.txt
    sudo systemctl restart $APP_NAME
    sudo systemctl status $APP_NAME
ENDSSH

echo "[SUCCESS] 部署完成!"
'''

        rollback = f'''#!/bin/bash
# Systemd 回滚脚本

APP_NAME="{name}"
SERVER="{user}@{host}"

ssh $SERVER "cd /opt/$APP_NAME && git checkout HEAD~1 && sudo systemctl restart $APP_NAME"

echo "[SUCCESS] 回滚完成!"
'''

        return deploy, rollback

    # ------------------------------------------------------------------
    # 健康检查
    # ------------------------------------------------------------------

    def _generate_health_check(
        self, server: Dict[str, Any], name: str
    ) -> str:
        """生成健康检查脚本。"""
        host = server.get("host", "localhost")
        port = server.get("port", 80)
        health_path = server.get("health_path", "/health")

        return f'''#!/bin/bash
# 健康检查脚本
# Generated by Leo Deployment Script Generator

URL="http://{host}:{port}{health_path}"
MAX_RETRIES=30
RETRY_INTERVAL=2

echo "[SEARCH] 检查服务健康状态..."

for i in $(seq 1 $MAX_RETRIES); do
    if curl -sf $URL > /dev/null; then
        echo "[SUCCESS] 服务健康!"
        exit 0
    fi
    echo "等待服务启动... ($i/$MAX_RETRIES)"
    sleep $RETRY_INTERVAL
done

echo "[ERROR] 服务启动失败!"
exit 1
'''


__all__ = ["DeploymentScriptGenerator"]
