"""
Flask API项目脚手架 Skill
========================
生成Flask API项目结构
"""

from pathlib import Path
from typing import Dict, List, Optional


class FlaskAPIScaffold:
    """Flask API项目脚手架"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        project_name: str,
        database_type: str = "mysql",
        features: List[str] = None
    ) -> Dict[str, str]:
        """
        生成Flask API项目结构

        Args:
            project_name: 项目名称
            database_type: 数据库类型
            features: 功能特性

        Returns:
            生成的文件字典
        """
        features = features or []

        return {
            'app_init': self._generate_app_init(project_name, database_type),
            'config': self._generate_config(database_type),
            'models_init': self._generate_models_init(),
            'api_init': self._generate_api_init(),
            'requirements': self._generate_requirements(database_type, features),
            'run': self._generate_run_file(),
            'dockerfile': self._generate_dockerfile(),
            'env_example': self._generate_env_example(database_type)
        }

    def _generate_app_init(self, name: str, db_type: str) -> str:
        """生成app/__init__.py"""
        return f'''"""
{name} Flask Application
Generated by Leo Flask API Scaffold
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS

from config import config

db = SQLAlchemy()
migrate = Migrate()


def create_app(config_name='development'):
    """Application Factory"""
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # 初始化扩展
    db.init_app(app)
    migrate.init_app(app, db)
    CORS(app)

    # 注册蓝图
    from app.api import api_bp
    app.register_blueprint(api_bp, url_prefix='/api')

    # 健康检查
    @app.route('/health')
    def health_check():
        return {{'status': 'healthy', 'app': '{name}'}}

    return app
'''

    def _generate_config(self, db_type: str) -> str:
        """生成config.py"""
        db_drivers = {
            'mysql': 'mysql+pymysql',
            'postgresql': 'postgresql',
            'sqlite': 'sqlite'
        }
        driver = db_drivers.get(db_type, 'mysql+pymysql')

        return f'''"""
Flask Configuration
Generated by Leo Flask API Scaffold
"""

import os
from datetime import timedelta


class Config:
    """Base Configuration"""
    SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    JSON_AS_ASCII = False


class DevelopmentConfig(Config):
    """Development Configuration"""
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = os.environ.get(
        'DATABASE_URL',
        '{driver}://root:password@localhost/db_dev'
    )


class ProductionConfig(Config):
    """Production Configuration"""
    DEBUG = False
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')


class TestingConfig(Config):
    """Testing Configuration"""
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'


config = {{
    'development': DevelopmentConfig,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': DevelopmentConfig
}}
'''

    def _generate_models_init(self) -> str:
        """生成app/models/__init__.py"""
        return '''"""
Database Models
"""

from app import db
from datetime import datetime


class BaseModel(db.Model):
    """Base Model with common fields"""
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        """Convert model to dictionary"""
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}
'''

    def _generate_api_init(self) -> str:
        """生成app/api/__init__.py"""
        return '''"""
API Blueprints
"""

from flask import Blueprint

api_bp = Blueprint('api', __name__)


@api_bp.route('/')
def api_index():
    return {'message': 'API is running'}


# 导入其他路由模块
# from app.api import users, products
'''

    def _generate_requirements(self, db_type: str, features: List[str]) -> str:
        """生成requirements.txt"""
        requirements = [
            'flask>=2.0.0',
            'flask-sqlalchemy>=3.0.0',
            'flask-migrate>=4.0.0',
            'flask-cors>=4.0.0',
            'python-dotenv>=1.0.0',
            'gunicorn>=21.0.0'
        ]

        if db_type == 'mysql':
            requirements.append('pymysql>=1.0.0')
        elif db_type == 'postgresql':
            requirements.append('psycopg2-binary>=2.9.0')

        if 'jwt' in features:
            requirements.append('flask-jwt-extended>=4.0.0')

        if 'redis' in features:
            requirements.append('redis>=4.0.0')

        return '\n'.join(requirements)

    def _generate_run_file(self) -> str:
        """生成run.py"""
        return '''"""
Run Flask Application
"""

import os
from app import create_app, db

app = create_app(os.getenv('FLASK_ENV', 'development'))


@app.shell_context_processor
def make_shell_context():
    return {'db': db}


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
'''

    def _generate_dockerfile(self) -> str:
        """生成Dockerfile"""
        return '''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "run:app"]
'''

    def _generate_env_example(self, db_type: str) -> str:
        """生成.env.example"""
        db_examples = {
            'mysql': 'mysql+pymysql://user:password@localhost/dbname',
            'postgresql': 'postgresql://user:password@localhost/dbname',
            'sqlite': 'sqlite:///app.db'
        }

        return f'''# Flask Configuration
FLASK_ENV=development
SECRET_KEY=your-secret-key

# Database
DATABASE_URL={db_examples.get(db_type, db_examples['mysql'])}

# JWT (if enabled)
JWT_SECRET_KEY=your-jwt-secret
'''


def main():
    """示例用法"""
    generator = FlaskAPIScaffold(output_dir="./output")

    results = generator.generate(
        project_name='my_api',
        database_type='mysql',
        features=['jwt', 'redis']
    )

    print("生成完成！")
    for name in results.keys():
        print(f"  - {name}")


if __name__ == '__main__':
    main()
