"""
miniprogram_component_generator_skill

微信小程序组件生成技能 - 生成小程序自定义组件的完整四件套（wxml/wxss/js/json）。
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

from leo_skills.core.base_executor import BaseExecutor


class MiniprogramComponentGenerator(BaseExecutor):
    """微信小程序组件生成器

    自动生成组件的四个文件：
    - WXML: 组件模板（支持多插槽）
    - WXSS: 组件样式
    - JS: 组件逻辑（含 properties / methods / lifetimes）
    - JSON: 组件配置
    """

    def __init__(self, output_dir: str = ".") -> None:
        self.name = "miniprogram_component_generator_skill"
        self.output_dir = Path(output_dir)

    # ------------------------------------------------------------------ #
    #  BaseExecutor 接口
    # ------------------------------------------------------------------ #

    def execute(
        self,
        action: str = "generate",
        context: Optional[Dict[str, Any]] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """执行技能入口

        Args:
            action: 动作类型，默认 "generate"
            context: 上下文参数（可包含 component_name / properties / methods / slots）
            **kwargs: 其他关键字参数
        """
        params: Dict[str, Any] = dict(context or {})
        params.update(kwargs)

        component_name = params.get("component_name", "custom-component")
        properties = params.get("properties", [])
        methods = params.get("methods", [])
        slots = params.get("slots", [])
        save = params.get("save", False)

        result = self.generate(
            component_name=component_name,
            properties=properties,
            methods=methods,
            slots=slots,
        )

        # 如果需要保存到文件
        if save:
            saved = self.save_files(component_name, result)
            return {
                "status": "success",
                "action": action,
                "data": result,
                "saved_files": {k: str(v) for k, v in saved.items()},
            }

        return {"status": "success", "action": action, "data": result}

    # ------------------------------------------------------------------ #
    #  核心生成逻辑
    # ------------------------------------------------------------------ #

    def generate(
        self,
        component_name: str,
        properties: Optional[List[Dict[str, Any]]] = None,
        methods: Optional[List[str]] = None,
        slots: Optional[List[str]] = None,
    ) -> Dict[str, str]:
        """生成小程序组件

        Args:
            component_name: 组件名称（如 'custom-card'）
            properties: 属性列表，每项为 {'name': ..., 'type': ..., 'default': ...}
            methods: 方法名称列表
            slots: 插槽名称列表

        Returns:
            {'wxml': ..., 'wxss': ..., 'js': ..., 'json': ...} 代码字典
        """
        properties = properties or []
        methods = methods or []
        slots = slots or []

        return {
            "wxml": self._generate_wxml(component_name, slots),
            "wxss": self._generate_wxss(component_name),
            "js": self._generate_js(component_name, properties, methods),
            "json": self._generate_json(component_name),
        }

    # ------------------------------------------------------------------ #
    #  WXML 模板生成
    # ------------------------------------------------------------------ #

    def _generate_wxml(self, name: str, slots: List[str]) -> str:
        """生成 WXML 模板"""
        slot_code = ""
        if slots:
            for slot in slots:
                slot_code += f'\n    <slot name="{slot}"></slot>'

        return f"""<!--
  {name} 组件
  Generated by Leo Miniprogram Component Generator
-->
<view class="{name}-container">
  <view class="{name}-content">
    <slot></slot>{slot_code}
  </view>
</view>
"""

    # ------------------------------------------------------------------ #
    #  WXSS 样式生成
    # ------------------------------------------------------------------ #

    def _generate_wxss(self, name: str) -> str:
        """生成 WXSS 样式"""
        return f"""/* {name} 组件样式 */
.{name}-container {{
  display: flex;
  flex-direction: column;
}}

.{name}-content {{
  padding: 20rpx;
}}
"""

    # ------------------------------------------------------------------ #
    #  JS 逻辑生成
    # ------------------------------------------------------------------ #

    def _generate_js(
        self,
        name: str,
        properties: List[Dict[str, Any]],
        methods: List[str],
    ) -> str:
        """生成 JS 组件逻辑"""
        # 生成 properties 定义
        props_code = []
        for prop in properties:
            prop_name = prop.get("name", "value")
            prop_type = prop.get("type", "String")
            prop_default = prop.get("default", '""' if prop_type == "String" else "null")
            props_code.append(
                f"    {prop_name}: {{\n"
                f"      type: {prop_type},\n"
                f"      value: {prop_default}\n"
                f"    }}"
            )
        props_str = ",\n".join(props_code) if props_code else ""

        # 生成 methods 定义
        methods_code = []
        for method in methods:
            methods_code.append(
                f"    {method}() {{\n"
                f"      // TODO: 实现 {method}\n"
                f"    }}"
            )
        methods_str = ",\n\n".join(methods_code) if methods_code else ""

        return f"""/**
 * {name} 组件
 * Generated by Leo Miniprogram Component Generator
 */
Component({{
  options: {{
    multipleSlots: true,
    styleIsolation: 'isolated'
  }},

  properties: {{
{props_str}
  }},

  data: {{
    // 组件内部数据
  }},

  lifetimes: {{
    attached() {{
      // 组件实例进入页面节点树时执行
    }},
    detached() {{
      // 组件实例被从页面节点树移除时执行
    }}
  }},

  methods: {{
{methods_str}
  }}
}})
"""

    # ------------------------------------------------------------------ #
    #  JSON 配置生成
    # ------------------------------------------------------------------ #

    def _generate_json(self, name: str) -> str:
        """生成 JSON 组件配置"""
        return """{
  "component": true,
  "usingComponents": {}
}
"""

    # ------------------------------------------------------------------ #
    #  文件保存
    # ------------------------------------------------------------------ #

    def save_files(self, name: str, results: Dict[str, str]) -> Dict[str, Path]:
        """将生成的组件代码保存到文件

        Args:
            name: 组件名称
            results: generate() 返回的代码字典

        Returns:
            {文件类型: 文件路径} 的字典
        """
        comp_dir = self.output_dir / "components" / name
        comp_dir.mkdir(parents=True, exist_ok=True)

        saved: Dict[str, Path] = {}
        extensions = {"wxml": ".wxml", "wxss": ".wxss", "js": ".js", "json": ".json"}

        for key, content in results.items():
            ext = extensions.get(key, f".{key}")
            file_path = comp_dir / f"{name}{ext}"
            file_path.write_text(content, encoding="utf-8")
            saved[key] = file_path

        return saved


__all__ = ["MiniprogramComponentGenerator"]
