"""
Lead Model
==================
Generated by Leo Database Model Generator
"""
from datetime import datetime
from app import db


class Lead(db.Model):
    """
    Lead数据模型

    Attributes:
        id: 主键ID
        name: name (string)
        phone: phone (string)
        parent_id: parent_id (integer)
        status: status (string)
        depth: depth (integer)
        created_at: 创建时间
        updated_at: 更新时间
    """
    __tablename__ = 'leads'

    # 主键
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    # 字段
    name = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(20), nullable=False)
    parent_id = db.Column(db.Integer, db.ForeignKey('leads.id'), nullable=True)
    status = db.Column(db.String(255), nullable=True, default='new')
    depth = db.Column(db.Integer, nullable=True, default=0)

    # 时间戳
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    parent = db.relationship('Lead', backref=db.backref('children', remote_side=[id]))
    # 索引
    __table_args__ = (
    db.Index('ix_leads_status', 'status'),
    db.Index('ix_leads_phone', 'phone'),
    )

    def to_dict(self) -> dict:
        """转换为字典"""
        return {
            'id': self.id,
            'name': self.name,
            'phone': self.phone,
            'parent_id': self.parent_id,
            'status': self.status,
            'depth': self.depth,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Lead':
        """从字典创建实例"""
        return cls(**{k: v for k, v in data.items() if hasattr(cls, k)})

    def update_from_dict(self, data: dict) -> None:
        """从字典更新实例"""
        for key, value in data.items():
            if hasattr(self, key) and key not in ('id', 'created_at', 'updated_at'):
                setattr(self, key, value)

    def __repr__(self) -> str:
        return f'<Lead {self.id}>'
