<template>
  <div class="data-table">
    <div v-if="loading" class="loading-wrapper">
      <span class="loading-spinner"></span>
    </div>
    <template v-else>
      <slot></slot>
      <slot name="header"></slot>
      <slot name="footer"></slot>
    </template>
  </div>
</template>

<script setup lang="ts">
/**
 * DataTable 组件
 * Generated by Leo Vue Component Generator
 */
import { ref, onMounted, onUnmounted } from 'vue'

interface Props {
  data: any[]
  columns: any[]
  loading?: boolean
  pagination?: boolean
}

const props = defineProps<Props>()

const emit = defineEmits<{  (e: 'row-click', value: any): void
  (e: 'page-change', value: any): void}>()

const loading = ref(false)

onMounted(() => {
  // 组件挂载后执行
})

onUnmounted(() => {
  // 组件卸载前执行
})
</script>

<style scoped lang="scss">
.data-table {
  position: relative;
}

.loading-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100px;
}

.loading-spinner {
  width: 24px;
  height: 24px;
  border: 2px solid #f3f3f3;
  border-top: 2px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
