"""
E2E测试生成器 Skill
==================
生成端到端测试代码（Playwright/Cypress）
"""

from pathlib import Path
from typing import Dict, Optional, List


class E2ETestGenerator:
    """E2E测试生成器"""

    def __init__(self, output_dir: str = ".", framework: str = "playwright"):
        self.output_dir = Path(output_dir)
        self.framework = framework.lower()

    def generate(
        self,
        test_name: str,
        user_flows: List[Dict],
        base_url: str = "http://localhost:3000"
    ) -> Dict[str, str]:
        """
        生成E2E测试

        Args:
            test_name: 测试名称
            user_flows: 用户流程列表
            base_url: 基础URL

        Returns:
            生成的测试代码字典
        """
        results = {}

        if self.framework == 'playwright':
            results['test'] = self._generate_playwright(test_name, user_flows, base_url)
            results['config'] = self._generate_playwright_config(base_url)
        else:
            results['test'] = self._generate_cypress(test_name, user_flows, base_url)
            results['config'] = self._generate_cypress_config(base_url)

        return results

    def _generate_playwright(self, test_name: str, flows: List[Dict], base_url: str) -> str:
        """生成Playwright测试"""
        test_cases = []

        for flow in flows:
            name = flow.get('name', 'unnamed flow')
            steps = flow.get('steps', [])

            step_code = []
            for step in steps:
                action = step.get('action', 'click')
                selector = step.get('selector', '')
                value = step.get('value', '')
                expected = step.get('expected', '')

                if action == 'goto':
                    step_code.append(f"    await page.goto('{value}')")
                elif action == 'click':
                    step_code.append(f"    await page.click('{selector}')")
                elif action == 'fill':
                    step_code.append(f"    await page.fill('{selector}', '{value}')")
                elif action == 'select':
                    step_code.append(f"    await page.selectOption('{selector}', '{value}')")
                elif action == 'wait':
                    step_code.append(f"    await page.waitForSelector('{selector}')")
                elif action == 'assert_text':
                    step_code.append(f"    await expect(page.locator('{selector}')).toContainText('{expected}')")
                elif action == 'assert_visible':
                    step_code.append(f"    await expect(page.locator('{selector}')).toBeVisible()")
                elif action == 'screenshot':
                    step_code.append(f"    await page.screenshot({{ path: '{value}' }})")

            steps_str = "\n".join(step_code)
            test_cases.append(f"""  test('{name}', async ({{ page }}) => {{
{steps_str}
  }})""")

        tests_str = "\n\n".join(test_cases)

        return f'''import {{ test, expect }} from '@playwright/test'

/**
 * {test_name} E2E Tests
 * Generated by Leo E2E Test Generator
 */
test.describe('{test_name}', () => {{
{tests_str}
}})
'''

    def _generate_playwright_config(self, base_url: str) -> str:
        """生成Playwright配置"""
        return f'''import {{ defineConfig, devices }} from '@playwright/test'

export default defineConfig({{
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',

  use: {{
    baseURL: '{base_url}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  }},

  projects: [
    {{
      name: 'chromium',
      use: {{ ...devices['Desktop Chrome'] }},
    }},
    {{
      name: 'firefox',
      use: {{ ...devices['Desktop Firefox'] }},
    }},
    {{
      name: 'webkit',
      use: {{ ...devices['Desktop Safari'] }},
    }},
    {{
      name: 'Mobile Chrome',
      use: {{ ...devices['Pixel 5'] }},
    }},
  ],

  webServer: {{
    command: 'npm run dev',
    url: '{base_url}',
    reuseExistingServer: !process.env.CI,
  }},
}})
'''

    def _generate_cypress(self, test_name: str, flows: List[Dict], base_url: str) -> str:
        """生成Cypress测试"""
        test_cases = []

        for flow in flows:
            name = flow.get('name', 'unnamed flow')
            steps = flow.get('steps', [])

            step_code = []
            for step in steps:
                action = step.get('action', 'click')
                selector = step.get('selector', '')
                value = step.get('value', '')
                expected = step.get('expected', '')

                if action == 'goto':
                    step_code.append(f"    cy.visit('{value}')")
                elif action == 'click':
                    step_code.append(f"    cy.get('{selector}').click()")
                elif action == 'fill':
                    step_code.append(f"    cy.get('{selector}').type('{value}')")
                elif action == 'select':
                    step_code.append(f"    cy.get('{selector}').select('{value}')")
                elif action == 'wait':
                    step_code.append(f"    cy.get('{selector}').should('exist')")
                elif action == 'assert_text':
                    step_code.append(f"    cy.get('{selector}').should('contain', '{expected}')")
                elif action == 'assert_visible':
                    step_code.append(f"    cy.get('{selector}').should('be.visible')")

            steps_str = "\n".join(step_code)
            test_cases.append(f"""  it('{name}', () => {{
{steps_str}
  }})""")

        tests_str = "\n\n".join(test_cases)

        return f'''/**
 * {test_name} E2E Tests
 * Generated by Leo E2E Test Generator
 */
describe('{test_name}', () => {{
{tests_str}
}})
'''

    def _generate_cypress_config(self, base_url: str) -> str:
        """生成Cypress配置"""
        return f'''import {{ defineConfig }} from 'cypress'

export default defineConfig({{
  e2e: {{
    baseUrl: '{base_url}',
    supportFile: 'cypress/support/e2e.ts',
    specPattern: 'cypress/e2e/**/*.cy.ts',
    viewportWidth: 1280,
    viewportHeight: 720,
    video: false,
    screenshotOnRunFailure: true,
  }},
}})
'''

    def save_files(self, test_name: str, results: Dict[str, str]) -> Dict[str, Path]:
        """保存生成的文件"""
        saved = {}

        if self.framework == 'playwright':
            e2e_dir = self.output_dir / 'e2e'
            e2e_dir.mkdir(parents=True, exist_ok=True)

            test_path = e2e_dir / f'{test_name}.spec.ts'
            test_path.write_text(results['test'], encoding='utf-8')
            saved['test'] = test_path

            config_path = self.output_dir / 'playwright.config.ts'
            config_path.write_text(results['config'], encoding='utf-8')
            saved['config'] = config_path
        else:
            cypress_dir = self.output_dir / 'cypress' / 'e2e'
            cypress_dir.mkdir(parents=True, exist_ok=True)

            test_path = cypress_dir / f'{test_name}.cy.ts'
            test_path.write_text(results['test'], encoding='utf-8')
            saved['test'] = test_path

            config_path = self.output_dir / 'cypress.config.ts'
            config_path.write_text(results['config'], encoding='utf-8')
            saved['config'] = config_path

        return saved


def main():
    """示例用法"""
    generator = E2ETestGenerator(output_dir="./output", framework="playwright")

    # 定义用户流程
    user_flows = [
        {
            'name': '用户注册流程',
            'steps': [
                {'action': 'goto', 'value': '/register'},
                {'action': 'fill', 'selector': 'input[name="name"]', 'value': '测试用户'},
                {'action': 'fill', 'selector': 'input[name="phone"]', 'value': '13800138000'},
                {'action': 'click', 'selector': 'button[type="submit"]'},
                {'action': 'assert_text', 'selector': '.success-message', 'expected': '注册成功'}
            ]
        },
        {
            'name': '用户登录流程',
            'steps': [
                {'action': 'goto', 'value': '/login'},
                {'action': 'fill', 'selector': 'input[name="phone"]', 'value': '13800138000'},
                {'action': 'fill', 'selector': 'input[name="code"]', 'value': '123456'},
                {'action': 'click', 'selector': 'button[type="submit"]'},
                {'action': 'assert_visible', 'selector': '.dashboard'}
            ]
        }
    ]

    results = generator.generate(
        test_name='auth',
        user_flows=user_flows,
        base_url='http://localhost:3000'
    )

    saved = generator.save_files('auth', results)
    print("生成完成！")
    for name, path in saved.items():
        print(f"  {name}: {path}")


if __name__ == '__main__':
    main()
