"""
Flask认证生成器 Skill
====================
生成Flask认证模块（JWT/Session）
"""

from pathlib import Path
from typing import Dict, Optional


class FlaskAuthGenerator:
    """Flask认证生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        auth_type: str = "jwt",
        user_model: str = "User",
        features: list = None
    ) -> Dict[str, str]:
        """
        生成Flask认证模块

        Args:
            auth_type: 认证类型 (jwt/session)
            user_model: 用户模型名称
            features: 功能特性列表

        Returns:
            生成的代码字典
        """
        features = features or []

        if auth_type == 'jwt':
            return self._generate_jwt_auth(user_model, features)
        else:
            return self._generate_session_auth(user_model, features)

    def _generate_jwt_auth(self, user_model: str, features: list) -> Dict[str, str]:
        """生成JWT认证"""
        blueprint = f'''"""
Flask JWT认证模块
Generated by Leo Flask Auth Generator
"""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import (
    create_access_token, create_refresh_token,
    jwt_required, get_jwt_identity
)
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import timedelta

auth_bp = Blueprint('auth', __name__, url_prefix='/api/auth')


@auth_bp.route('/register', methods=['POST'])
def register():
    """用户注册"""
    data = request.get_json()

    # 验证必填字段
    if not data.get('username') or not data.get('password'):
        return jsonify({{'error': '用户名和密码必填'}}), 400

    # TODO: 检查用户是否已存在
    # TODO: 创建用户

    return jsonify({{'message': '注册成功'}}), 201


@auth_bp.route('/login', methods=['POST'])
def login():
    """用户登录"""
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')

    # TODO: 验证用户
    # user = {user_model}.query.filter_by(username=username).first()
    # if not user or not check_password_hash(user.password, password):
    #     return jsonify({{'error': '用户名或密码错误'}}), 401

    # 生成Token
    access_token = create_access_token(
        identity=username,
        expires_delta=timedelta(hours=1)
    )
    refresh_token = create_refresh_token(identity=username)

    return jsonify({{
        'access_token': access_token,
        'refresh_token': refresh_token
    }})


@auth_bp.route('/refresh', methods=['POST'])
@jwt_required(refresh=True)
def refresh():
    """刷新Token"""
    identity = get_jwt_identity()
    access_token = create_access_token(identity=identity)
    return jsonify({{'access_token': access_token}})


@auth_bp.route('/me', methods=['GET'])
@jwt_required()
def get_current_user():
    """获取当前用户信息"""
    identity = get_jwt_identity()
    # TODO: 返回用户信息
    return jsonify({{'username': identity}})


@auth_bp.route('/logout', methods=['POST'])
@jwt_required()
def logout():
    """用户登出"""
    # JWT是无状态的，客户端删除token即可
    # 如需服务端失效，可使用token黑名单
    return jsonify({{'message': '登出成功'}})
'''

        middleware = '''"""
JWT认证中间件
"""

from functools import wraps
from flask import jsonify
from flask_jwt_extended import verify_jwt_in_request, get_jwt_identity


def admin_required(fn):
    """管理员权限装饰器"""
    @wraps(fn)
    def wrapper(*args, **kwargs):
        verify_jwt_in_request()
        identity = get_jwt_identity()
        # TODO: 检查用户是否是管理员
        return fn(*args, **kwargs)
    return wrapper


def permission_required(permission):
    """权限检查装饰器"""
    def decorator(fn):
        @wraps(fn)
        def wrapper(*args, **kwargs):
            verify_jwt_in_request()
            identity = get_jwt_identity()
            # TODO: 检查用户是否有指定权限
            return fn(*args, **kwargs)
        return wrapper
    return decorator
'''

        config = '''"""
JWT配置
"""

import os
from datetime import timedelta


class JWTConfig:
    JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY', 'your-secret-key')
    JWT_ACCESS_TOKEN_EXPIRES = timedelta(hours=1)
    JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=30)
    JWT_TOKEN_LOCATION = ['headers']
    JWT_HEADER_NAME = 'Authorization'
    JWT_HEADER_TYPE = 'Bearer'
'''

        return {
            'blueprint': blueprint,
            'middleware': middleware,
            'config': config
        }

    def _generate_session_auth(self, user_model: str, features: list) -> Dict[str, str]:
        """生成Session认证"""
        blueprint = f'''"""
Flask Session认证模块
Generated by Leo Flask Auth Generator
"""

from flask import Blueprint, request, jsonify, session
from werkzeug.security import generate_password_hash, check_password_hash

auth_bp = Blueprint('auth', __name__, url_prefix='/api/auth')


@auth_bp.route('/register', methods=['POST'])
def register():
    """用户注册"""
    data = request.get_json()

    if not data.get('username') or not data.get('password'):
        return jsonify({{'error': '用户名和密码必填'}}), 400

    # TODO: 创建用户
    return jsonify({{'message': '注册成功'}}), 201


@auth_bp.route('/login', methods=['POST'])
def login():
    """用户登录"""
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')

    # TODO: 验证用户

    session['user_id'] = 1  # TODO: 使用实际用户ID
    session['username'] = username

    return jsonify({{'message': '登录成功'}})


@auth_bp.route('/logout', methods=['POST'])
def logout():
    """用户登出"""
    session.clear()
    return jsonify({{'message': '登出成功'}})


@auth_bp.route('/me', methods=['GET'])
def get_current_user():
    """获取当前用户"""
    if 'user_id' not in session:
        return jsonify({{'error': '未登录'}}), 401

    return jsonify({{
        'user_id': session['user_id'],
        'username': session['username']
    }})
'''

        middleware = '''"""
Session认证中间件
"""

from functools import wraps
from flask import session, jsonify


def login_required(fn):
    """登录验证装饰器"""
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if 'user_id' not in session:
            return jsonify({'error': '请先登录'}), 401
        return fn(*args, **kwargs)
    return wrapper
'''

        return {
            'blueprint': blueprint,
            'middleware': middleware
        }


def main():
    """示例用法"""
    generator = FlaskAuthGenerator(output_dir="./output")

    results = generator.generate(
        auth_type='jwt',
        user_model='User',
        features=['refresh_token', 'role_based']
    )

    print("生成完成！")
    for name in results.keys():
        print(f"  - {name}")


if __name__ == '__main__':
    main()
