"""
部署脚本生成器 Skill
==================
生成部署和回滚脚本
"""

from pathlib import Path
from typing import Dict, Optional


class DeploymentScriptGenerator:
    """部署脚本生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        server_info: Dict,
        deploy_type: str = "docker",
        project_name: str = "app"
    ) -> Dict[str, str]:
        """
        生成部署脚本

        Args:
            server_info: 服务器信息
            deploy_type: 部署类型 (docker/pm2/systemd)
            project_name: 项目名称

        Returns:
            生成的脚本字典
        """
        generators = {
            'docker': self._generate_docker_deploy,
            'pm2': self._generate_pm2_deploy,
            'systemd': self._generate_systemd_deploy
        }

        generator = generators.get(deploy_type, self._generate_docker_deploy)
        deploy_script, rollback_script = generator(server_info, project_name)

        return {
            'deploy': deploy_script,
            'rollback': rollback_script,
            'health_check': self._generate_health_check(server_info, project_name)
        }

    def _generate_docker_deploy(self, server: Dict, name: str) -> tuple:
        """生成Docker部署脚本"""
        host = server.get('host', 'localhost')
        user = server.get('user', 'root')
        registry = server.get('registry', 'docker.io')

        deploy = f'''#!/bin/bash
# Docker部署脚本
# Generated by Leo Deployment Script Generator

set -e

# 配置
APP_NAME="{name}"
SERVER="{user}@{host}"
REGISTRY="{registry}"
IMAGE="$REGISTRY/$APP_NAME:${{TAG:-latest}}"

echo "[LAUNCH] 开始部署 $APP_NAME"

# 1. 构建镜像
echo "📦 构建Docker镜像..."
docker build -t $IMAGE .

# 2. 推送镜像
echo "⬆️  推送镜像到仓库..."
docker push $IMAGE

# 3. 远程部署
echo "🔄 远程部署..."
ssh $SERVER << 'ENDSSH'
    cd /opt/$APP_NAME

    # 备份当前版本
    docker tag $IMAGE $IMAGE.backup 2>/dev/null || true

    # 拉取新镜像
    docker pull $IMAGE

    # 停止旧容器
    docker-compose down

    # 启动新容器
    docker-compose up -d

    # 清理旧镜像
    docker image prune -f
ENDSSH

echo "[SUCCESS] 部署完成!"
'''

        rollback = f'''#!/bin/bash
# Docker回滚脚本
# Generated by Leo Deployment Script Generator

set -e

APP_NAME="{name}"
SERVER="{user}@{host}"
REGISTRY="{registry}"
IMAGE="$REGISTRY/$APP_NAME"

echo "⏪ 开始回滚 $APP_NAME"

ssh $SERVER << 'ENDSSH'
    cd /opt/$APP_NAME

    # 停止当前版本
    docker-compose down

    # 恢复备份版本
    docker tag $IMAGE.backup $IMAGE:latest

    # 启动备份版本
    docker-compose up -d
ENDSSH

echo "[SUCCESS] 回滚完成!"
'''

        return deploy, rollback

    def _generate_pm2_deploy(self, server: Dict, name: str) -> tuple:
        """生成PM2部署脚本"""
        host = server.get('host', 'localhost')
        user = server.get('user', 'root')
        path = server.get('path', f'/opt/{name}')

        deploy = f'''#!/bin/bash
# PM2部署脚本
# Generated by Leo Deployment Script Generator

set -e

APP_NAME="{name}"
SERVER="{user}@{host}"
DEPLOY_PATH="{path}"

echo "[LAUNCH] 开始部署 $APP_NAME"

# 同步代码
rsync -avz --exclude 'node_modules' --exclude '.git' ./ $SERVER:$DEPLOY_PATH/

# 远程安装依赖和重启
ssh $SERVER << 'ENDSSH'
    cd $DEPLOY_PATH
    npm install --production
    pm2 reload ecosystem.config.js --env production
ENDSSH

echo "[SUCCESS] 部署完成!"
'''

        rollback = f'''#!/bin/bash
# PM2回滚脚本

APP_NAME="{name}"
SERVER="{user}@{host}"

ssh $SERVER "cd {path} && git checkout HEAD~1 && pm2 reload all"

echo "[SUCCESS] 回滚完成!"
'''

        return deploy, rollback

    def _generate_systemd_deploy(self, server: Dict, name: str) -> tuple:
        """生成Systemd部署脚本"""
        host = server.get('host', 'localhost')
        user = server.get('user', 'root')

        deploy = f'''#!/bin/bash
# Systemd部署脚本
# Generated by Leo Deployment Script Generator

set -e

APP_NAME="{name}"
SERVER="{user}@{host}"

echo "[LAUNCH] 开始部署 $APP_NAME"

# 同步代码
rsync -avz ./ $SERVER:/opt/$APP_NAME/

# 远程重启服务
ssh $SERVER << 'ENDSSH'
    cd /opt/$APP_NAME
    pip install -r requirements.txt
    sudo systemctl restart $APP_NAME
    sudo systemctl status $APP_NAME
ENDSSH

echo "[SUCCESS] 部署完成!"
'''

        rollback = f'''#!/bin/bash
# Systemd回滚脚本

APP_NAME="{name}"
SERVER="{user}@{host}"

ssh $SERVER "cd /opt/$APP_NAME && git checkout HEAD~1 && sudo systemctl restart $APP_NAME"

echo "[SUCCESS] 回滚完成!"
'''

        return deploy, rollback

    def _generate_health_check(self, server: Dict, name: str) -> str:
        """生成健康检查脚本"""
        host = server.get('host', 'localhost')
        port = server.get('port', 80)
        health_path = server.get('health_path', '/health')

        return f'''#!/bin/bash
# 健康检查脚本
# Generated by Leo Deployment Script Generator

URL="http://{host}:{port}{health_path}"
MAX_RETRIES=30
RETRY_INTERVAL=2

echo "[SEARCH] 检查服务健康状态..."

for i in $(seq 1 $MAX_RETRIES); do
    if curl -sf $URL > /dev/null; then
        echo "[SUCCESS] 服务健康!"
        exit 0
    fi
    echo "等待服务启动... ($i/$MAX_RETRIES)"
    sleep $RETRY_INTERVAL
done

echo "[ERROR] 服务启动失败!"
exit 1
'''


def main():
    """示例用法"""
    generator = DeploymentScriptGenerator(output_dir="./output")

    results = generator.generate(
        server_info={
            'host': '192.168.1.100',
            'user': 'deploy',
            'registry': 'registry.example.com',
            'port': 8080,
            'health_path': '/api/health'
        },
        deploy_type='docker',
        project_name='my-app'
    )

    print("生成完成！")
    for name in results.keys():
        print(f"  - {name}")


if __name__ == '__main__':
    main()
