"""
GitHub Actions生成器 Skill
=========================
生成GitHub Actions CI/CD工作流配置
"""

from pathlib import Path
from typing import Dict, Optional, List
import yaml


class GitHubActionsGenerator:
    """GitHub Actions工作流生成器"""

    TEMPLATES = {
        'python-ci': {
            'name': 'Python CI',
            'triggers': ['push', 'pull_request'],
            'python_version': '3.9'
        },
        'node-ci': {
            'name': 'Node.js CI',
            'triggers': ['push', 'pull_request'],
            'node_version': '18'
        },
        'docker-build': {
            'name': 'Docker Build',
            'triggers': ['push'],
            'registry': 'ghcr.io'
        },
        'deploy': {
            'name': 'Deploy',
            'triggers': ['push'],
            'environment': 'production'
        }
    }

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        workflow_type: str,
        project_name: str,
        options: Optional[Dict] = None
    ) -> Dict[str, str]:
        """
        生成GitHub Actions工作流

        Args:
            workflow_type: 工作流类型
            project_name: 项目名称
            options: 额外选项

        Returns:
            生成的配置字典
        """
        options = options or {}

        results = {}

        if workflow_type == 'python-ci':
            results['ci'] = self._generate_python_ci(project_name, options)
        elif workflow_type == 'node-ci':
            results['ci'] = self._generate_node_ci(project_name, options)
        elif workflow_type == 'docker-build':
            results['docker'] = self._generate_docker_build(project_name, options)
        elif workflow_type == 'deploy':
            results['deploy'] = self._generate_deploy(project_name, options)
        elif workflow_type == 'full':
            results['ci'] = self._generate_python_ci(project_name, options)
            results['docker'] = self._generate_docker_build(project_name, options)
            results['deploy'] = self._generate_deploy(project_name, options)

        return results

    def _generate_python_ci(self, project_name: str, options: Dict) -> str:
        """生成Python CI工作流"""
        python_version = options.get('python_version', '3.9')
        test_command = options.get('test_command', 'pytest')

        workflow = {
            'name': 'Python CI',
            'on': {
                'push': {'branches': ['main', 'master', 'develop']},
                'pull_request': {'branches': ['main', 'master']}
            },
            'jobs': {
                'test': {
                    'runs-on': 'ubuntu-latest',
                    'steps': [
                        {'uses': 'actions/checkout@v4'},
                        {
                            'name': 'Set up Python',
                            'uses': 'actions/setup-python@v5',
                            'with': {'python-version': python_version}
                        },
                        {
                            'name': 'Cache pip',
                            'uses': 'actions/cache@v4',
                            'with': {
                                'path': '~/.cache/pip',
                                'key': "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
                            }
                        },
                        {
                            'name': 'Install dependencies',
                            'run': 'pip install -r requirements.txt'
                        },
                        {
                            'name': 'Lint with flake8',
                            'run': 'pip install flake8 && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics'
                        },
                        {
                            'name': 'Run tests',
                            'run': f'pip install pytest pytest-cov && {test_command} --cov=./ --cov-report=xml'
                        },
                        {
                            'name': 'Upload coverage',
                            'uses': 'codecov/codecov-action@v4',
                            'with': {'file': './coverage.xml'}
                        }
                    ]
                }
            }
        }

        return f"# {project_name} CI\n# Generated by Leo GitHub Actions Generator\n\n" + yaml.dump(workflow, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _generate_node_ci(self, project_name: str, options: Dict) -> str:
        """生成Node.js CI工作流"""
        node_version = options.get('node_version', '18')

        workflow = {
            'name': 'Node.js CI',
            'on': {
                'push': {'branches': ['main', 'master']},
                'pull_request': {'branches': ['main', 'master']}
            },
            'jobs': {
                'build': {
                    'runs-on': 'ubuntu-latest',
                    'steps': [
                        {'uses': 'actions/checkout@v4'},
                        {
                            'name': 'Setup Node.js',
                            'uses': 'actions/setup-node@v4',
                            'with': {
                                'node-version': node_version,
                                'cache': 'npm'
                            }
                        },
                        {'name': 'Install dependencies', 'run': 'npm ci'},
                        {'name': 'Lint', 'run': 'npm run lint --if-present'},
                        {'name': 'Test', 'run': 'npm test'},
                        {'name': 'Build', 'run': 'npm run build'}
                    ]
                }
            }
        }

        return f"# {project_name} CI\n\n" + yaml.dump(workflow, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _generate_docker_build(self, project_name: str, options: Dict) -> str:
        """生成Docker构建工作流"""
        registry = options.get('registry', 'ghcr.io')
        image_name = project_name.lower().replace(' ', '-')

        workflow = {
            'name': 'Docker Build',
            'on': {
                'push': {
                    'branches': ['main'],
                    'tags': ['v*']
                }
            },
            'env': {
                'REGISTRY': registry,
                'IMAGE_NAME': '${{ github.repository }}'
            },
            'jobs': {
                'build-and-push': {
                    'runs-on': 'ubuntu-latest',
                    'permissions': {
                        'contents': 'read',
                        'packages': 'write'
                    },
                    'steps': [
                        {'uses': 'actions/checkout@v4'},
                        {
                            'name': 'Set up Docker Buildx',
                            'uses': 'docker/setup-buildx-action@v3'
                        },
                        {
                            'name': 'Login to Registry',
                            'uses': 'docker/login-action@v3',
                            'with': {
                                'registry': '${{ env.REGISTRY }}',
                                'username': '${{ github.actor }}',
                                'password': '${{ secrets.GITHUB_TOKEN }}'
                            }
                        },
                        {
                            'name': 'Extract metadata',
                            'id': 'meta',
                            'uses': 'docker/metadata-action@v5',
                            'with': {
                                'images': '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
                            }
                        },
                        {
                            'name': 'Build and push',
                            'uses': 'docker/build-push-action@v5',
                            'with': {
                                'context': '.',
                                'push': True,
                                'tags': '${{ steps.meta.outputs.tags }}',
                                'labels': '${{ steps.meta.outputs.labels }}',
                                'cache-from': 'type=gha',
                                'cache-to': 'type=gha,mode=max'
                            }
                        }
                    ]
                }
            }
        }

        return f"# {project_name} Docker Build\n\n" + yaml.dump(workflow, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def _generate_deploy(self, project_name: str, options: Dict) -> str:
        """生成部署工作流"""
        environment = options.get('environment', 'production')
        deploy_method = options.get('deploy_method', 'ssh')

        workflow = {
            'name': 'Deploy',
            'on': {
                'push': {'branches': ['main']},
                'workflow_dispatch': None
            },
            'jobs': {
                'deploy': {
                    'runs-on': 'ubuntu-latest',
                    'environment': environment,
                    'steps': [
                        {'uses': 'actions/checkout@v4'},
                        {
                            'name': 'Deploy to server',
                            'uses': 'appleboy/ssh-action@v1.0.3',
                            'with': {
                                'host': '${{ secrets.SERVER_HOST }}',
                                'username': '${{ secrets.SERVER_USER }}',
                                'key': '${{ secrets.SSH_PRIVATE_KEY }}',
                                'script': '''
cd /var/www/${{ github.repository }}
git pull origin main
docker-compose pull
docker-compose up -d
'''
                            }
                        },
                        {
                            'name': 'Health check',
                            'run': 'curl -f ${{ secrets.HEALTH_CHECK_URL }} || exit 1'
                        }
                    ]
                }
            }
        }

        return f"# {project_name} Deploy\n\n" + yaml.dump(workflow, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def save_files(self, results: Dict[str, str]) -> Dict[str, Path]:
        """保存生成的文件"""
        saved = {}
        workflows_dir = self.output_dir / '.github' / 'workflows'
        workflows_dir.mkdir(parents=True, exist_ok=True)

        file_mapping = {
            'ci': 'ci.yml',
            'docker': 'docker.yml',
            'deploy': 'deploy.yml'
        }

        for key, filename in file_mapping.items():
            if key in results:
                file_path = workflows_dir / filename
                file_path.write_text(results[key], encoding='utf-8')
                saved[key] = file_path

        return saved


def main():
    """示例用法"""
    generator = GitHubActionsGenerator(output_dir="./output")

    results = generator.generate(
        workflow_type='full',
        project_name='MyProject',
        options={
            'python_version': '3.11',
            'test_command': 'pytest -v'
        }
    )

    saved = generator.save_files(results)
    print("生成完成！")
    for name, path in saved.items():
        print(f"  {name}: {path}")


if __name__ == '__main__':
    main()
