"""
API文档生成器 Skill
==================
生成API文档（OpenAPI/Swagger/Markdown）
"""

from pathlib import Path
from typing import Dict, List, Optional
import json


class APIDocGenerator:
    """API文档生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        api_routes: List[Dict],
        title: str = "API Documentation",
        version: str = "1.0.0"
    ) -> Dict[str, str]:
        """
        生成API文档

        Args:
            api_routes: API路由列表
            title: 文档标题
            version: API版本

        Returns:
            生成的文档字典
        """
        return {
            'openapi': self._generate_openapi(api_routes, title, version),
            'markdown': self._generate_markdown(api_routes, title, version)
        }

    def _generate_openapi(self, routes: List[Dict], title: str, version: str) -> str:
        """生成OpenAPI规范"""
        paths = {}

        for route in routes:
            path = route.get('path', '/')
            method = route.get('method', 'GET').lower()
            desc = route.get('description', '')
            params = route.get('parameters', [])
            request_body = route.get('request_body')
            responses = route.get('responses', {'200': {'description': 'Success'}})

            if path not in paths:
                paths[path] = {}

            operation = {
                'summary': desc,
                'responses': responses
            }

            if params:
                operation['parameters'] = params

            if request_body and method in ['post', 'put', 'patch']:
                operation['requestBody'] = {
                    'content': {
                        'application/json': {
                            'schema': request_body
                        }
                    }
                }

            paths[path][method] = operation

        openapi_spec = {
            'openapi': '3.0.0',
            'info': {
                'title': title,
                'version': version,
                'description': f'{title} - Generated by Leo API Doc Generator'
            },
            'paths': paths
        }

        return json.dumps(openapi_spec, indent=2, ensure_ascii=False)

    def _generate_markdown(self, routes: List[Dict], title: str, version: str) -> str:
        """生成Markdown文档"""
        lines = [
            f'# {title}',
            '',
            f'**版本**: {version}',
            '',
            '*Generated by Leo API Doc Generator*',
            '',
            '---',
            '',
            '## 接口列表',
            '',
            '| 方法 | 路径 | 描述 |',
            '|------|------|------|'
        ]

        for route in routes:
            method = route.get('method', 'GET')
            path = route.get('path', '/')
            desc = route.get('description', '')
            lines.append(f'| {method} | `{path}` | {desc} |')

        lines.extend(['', '---', '', '## 接口详情', ''])

        for route in routes:
            method = route.get('method', 'GET')
            path = route.get('path', '/')
            desc = route.get('description', '')
            params = route.get('parameters', [])
            request_body = route.get('request_body')

            lines.extend([
                f'### {method} {path}',
                '',
                f'**描述**: {desc}',
                ''
            ])

            if params:
                lines.extend([
                    '**参数**:',
                    '',
                    '| 名称 | 位置 | 类型 | 必填 | 描述 |',
                    '|------|------|------|------|------|'
                ])
                for param in params:
                    name = param.get('name', '')
                    location = param.get('in', 'query')
                    ptype = param.get('schema', {}).get('type', 'string')
                    required = '是' if param.get('required') else '否'
                    pdesc = param.get('description', '')
                    lines.append(f'| {name} | {location} | {ptype} | {required} | {pdesc} |')
                lines.append('')

            if request_body:
                lines.extend([
                    '**请求体**:',
                    '',
                    '```json',
                    json.dumps(request_body, indent=2, ensure_ascii=False),
                    '```',
                    ''
                ])

            lines.extend([
                '**响应示例**:',
                '',
                '```json',
                '{',
                '  "code": 200,',
                '  "message": "success",',
                '  "data": {}',
                '}',
                '```',
                '',
                '---',
                ''
            ])

        return '\n'.join(lines)


def main():
    """示例用法"""
    generator = APIDocGenerator(output_dir="./output")

    api_routes = [
        {
            'method': 'GET',
            'path': '/api/users',
            'description': '获取用户列表',
            'parameters': [
                {'name': 'page', 'in': 'query', 'schema': {'type': 'integer'}, 'description': '页码'},
                {'name': 'limit', 'in': 'query', 'schema': {'type': 'integer'}, 'description': '每页数量'}
            ]
        },
        {
            'method': 'POST',
            'path': '/api/users',
            'description': '创建用户',
            'request_body': {
                'type': 'object',
                'properties': {
                    'name': {'type': 'string'},
                    'email': {'type': 'string'}
                }
            }
        }
    ]

    results = generator.generate(
        api_routes=api_routes,
        title='用户管理API',
        version='1.0.0'
    )

    print("生成完成！")
    print("\n=== Markdown ===")
    print(results['markdown'][:500])


if __name__ == '__main__':
    main()
