"""
Vue页面生成器 Skill
==================
生成完整的Vue3页面（含路由配置）
"""

from pathlib import Path
from typing import Dict, List, Optional


class VuePageGenerator:
    """Vue页面生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        page_name: str,
        layout_type: str = "default",
        api_endpoints: List[Dict] = None,
        features: List[str] = None
    ) -> Dict[str, str]:
        """
        生成Vue页面

        Args:
            page_name: 页面名称
            layout_type: 布局类型 (default/sidebar/dashboard)
            api_endpoints: API端点列表
            features: 功能特性列表

        Returns:
            生成的代码字典
        """
        api_endpoints = api_endpoints or []
        features = features or []

        results = {}
        results['page'] = self._generate_page(page_name, layout_type, api_endpoints, features)
        results['types'] = self._generate_types(page_name, api_endpoints)
        results['router'] = self._generate_router_config(page_name)

        if 'store' in features:
            results['store'] = self._generate_store_module(page_name, api_endpoints)

        return results

    def _generate_page(self, name: str, layout: str, endpoints: List[Dict], features: List[str]) -> str:
        """生成Vue页面组件"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))

        # 生成API调用代码
        api_imports = []
        api_calls = []
        for ep in endpoints:
            method = ep.get('method', 'GET').lower()
            path = ep.get('path', '')
            func_name = ep.get('name', f'{method}Data')
            api_imports.append(f"import {{ {func_name} }} from '@/api/{name}'")
            api_calls.append(f"""
const {func_name}Result = ref(null)
const fetch{func_name.capitalize()} = async () => {{
  try {{
    {func_name}Result.value = await {func_name}()
  }} catch (error) {{
    console.error('API Error:', error)
  }}
}}""")

        api_imports_str = '\n'.join(api_imports) if api_imports else ''
        api_calls_str = '\n'.join(api_calls) if api_calls else ''

        # 布局模板
        layout_templates = {
            'default': '<div class="page-container">',
            'sidebar': '<div class="page-with-sidebar"><aside class="sidebar"></aside><main class="main-content">',
            'dashboard': '<div class="dashboard-layout"><header class="dashboard-header"></header><main class="dashboard-content">'
        }
        layout_open = layout_templates.get(layout, layout_templates['default'])
        layout_close = '</div>' if layout == 'default' else '</main></div>'

        return f'''<template>
  {layout_open}
    <h1>{pascal_name}</h1>
    <div class="content">
      <!-- 页面内容 -->
    </div>
  {layout_close}
</template>

<script setup lang="ts">
import {{ ref, onMounted }} from 'vue'
import type {{ {pascal_name}Data }} from '@/types/{name}'
{api_imports_str}

// 响应式数据
const loading = ref(false)
const data = ref<{pascal_name}Data | null>(null)
{api_calls_str}

// 生命周期
onMounted(() => {{
  // 初始化逻辑
}})
</script>

<style scoped lang="scss">
.page-container {{
  padding: 20px;
}}

.content {{
  margin-top: 20px;
}}
</style>
'''

    def _generate_types(self, name: str, endpoints: List[Dict]) -> str:
        """生成类型定义"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))

        return f'''/**
 * {pascal_name} 页面类型定义
 * Generated by Leo Vue Page Generator
 */

export interface {pascal_name}Data {{
  id: number
  // 添加其他字段
}}

export interface {pascal_name}Query {{
  page?: number
  pageSize?: number
  // 添加查询参数
}}

export interface {pascal_name}Response {{
  data: {pascal_name}Data[]
  total: number
}}
'''

    def _generate_router_config(self, name: str) -> str:
        """生成路由配置"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))
        kebab_name = name.replace('_', '-')

        return f'''// 添加到 router/index.ts
{{
  path: '/{kebab_name}',
  name: '{pascal_name}',
  component: () => import('@/views/{name}/{pascal_name}.vue'),
  meta: {{
    title: '{pascal_name}',
    requiresAuth: true
  }}
}}
'''

    def _generate_store_module(self, name: str, endpoints: List[Dict]) -> str:
        """生成Pinia Store模块"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))

        return f'''import {{ defineStore }} from 'pinia'
import type {{ {pascal_name}Data }} from '@/types/{name}'

export const use{pascal_name}Store = defineStore('{name}', {{
  state: () => ({{
    data: null as {pascal_name}Data | null,
    list: [] as {pascal_name}Data[],
    loading: false,
    error: null as string | null
  }}),

  getters: {{
    isEmpty: (state) => state.list.length === 0
  }},

  actions: {{
    async fetchData() {{
      this.loading = true
      try {{
        // API调用
        this.loading = false
      }} catch (error) {{
        this.error = String(error)
        this.loading = false
      }}
    }}
  }}
}})
'''


def main():
    """示例用法"""
    generator = VuePageGenerator(output_dir="./output")

    results = generator.generate(
        page_name='user_list',
        layout_type='dashboard',
        api_endpoints=[
            {'method': 'GET', 'path': '/users', 'name': 'getUsers'},
            {'method': 'POST', 'path': '/users', 'name': 'createUser'}
        ],
        features=['store']
    )

    print("生成完成！")
    for name, content in results.items():
        print(f"\n=== {name} ===")
        print(content[:200] + "...")


if __name__ == '__main__':
    main()
