"""
FastAPI端点生成器 Skill
=====================
生成FastAPI端点代码
"""

from pathlib import Path
from typing import Dict, List, Optional


class FastAPIEndpointGenerator:
    """FastAPI端点生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        resource_name: str,
        endpoints: List[Dict] = None,
        pydantic_models: List[Dict] = None
    ) -> Dict[str, str]:
        """
        生成FastAPI端点

        Args:
            resource_name: 资源名称
            endpoints: 端点列表
            pydantic_models: Pydantic模型列表

        Returns:
            生成的代码字典
        """
        endpoints = endpoints or [
            {'method': 'GET', 'path': '/', 'description': '获取列表'},
            {'method': 'GET', 'path': '/{id}', 'description': '获取详情'},
            {'method': 'POST', 'path': '/', 'description': '创建'},
            {'method': 'PUT', 'path': '/{id}', 'description': '更新'},
            {'method': 'DELETE', 'path': '/{id}', 'description': '删除'}
        ]

        return {
            'router': self._generate_router(resource_name, endpoints),
            'schemas': self._generate_schemas(resource_name, pydantic_models),
            'crud': self._generate_crud(resource_name)
        }

    def _generate_router(self, name: str, endpoints: List[Dict]) -> str:
        """生成路由"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))

        endpoint_code = []
        for ep in endpoints:
            method = ep.get('method', 'GET').lower()
            path = ep.get('path', '/')
            desc = ep.get('description', '')

            if method == 'get' and '{id}' not in path:
                endpoint_code.append(f'''
@router.get("/", response_model=List[{pascal_name}Response])
async def list_{name}s(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db)
):
    """{desc}"""
    return crud.get_{name}s(db, skip=skip, limit=limit)
''')
            elif method == 'get':
                endpoint_code.append(f'''
@router.get("/{{id}}", response_model={pascal_name}Response)
async def get_{name}(id: int, db: Session = Depends(get_db)):
    """{desc}"""
    db_item = crud.get_{name}(db, id=id)
    if db_item is None:
        raise HTTPException(status_code=404, detail="{pascal_name} not found")
    return db_item
''')
            elif method == 'post':
                endpoint_code.append(f'''
@router.post("/", response_model={pascal_name}Response, status_code=201)
async def create_{name}(
    item: {pascal_name}Create,
    db: Session = Depends(get_db)
):
    """{desc}"""
    return crud.create_{name}(db, item=item)
''')
            elif method == 'put':
                endpoint_code.append(f'''
@router.put("/{{id}}", response_model={pascal_name}Response)
async def update_{name}(
    id: int,
    item: {pascal_name}Update,
    db: Session = Depends(get_db)
):
    """{desc}"""
    db_item = crud.update_{name}(db, id=id, item=item)
    if db_item is None:
        raise HTTPException(status_code=404, detail="{pascal_name} not found")
    return db_item
''')
            elif method == 'delete':
                endpoint_code.append(f'''
@router.delete("/{{id}}")
async def delete_{name}(id: int, db: Session = Depends(get_db)):
    """{desc}"""
    success = crud.delete_{name}(db, id=id)
    if not success:
        raise HTTPException(status_code=404, detail="{pascal_name} not found")
    return {{"message": "Deleted successfully"}}
''')

        endpoints_str = '\n'.join(endpoint_code)

        return f'''"""
{pascal_name} API Router
Generated by Leo FastAPI Endpoint Generator
"""

from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database import get_db
from app.schemas.{name} import {pascal_name}Create, {pascal_name}Update, {pascal_name}Response
from app.crud import {name} as crud

router = APIRouter(prefix="/{name}s", tags=["{pascal_name}s"])
{endpoints_str}
'''

    def _generate_schemas(self, name: str, models: List[Dict] = None) -> str:
        """生成Pydantic模型"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))

        return f'''"""
{pascal_name} Pydantic Schemas
Generated by Leo FastAPI Endpoint Generator
"""

from typing import Optional
from datetime import datetime
from pydantic import BaseModel


class {pascal_name}Base(BaseModel):
    """基础模型"""
    name: str
    description: Optional[str] = None


class {pascal_name}Create({pascal_name}Base):
    """创建模型"""
    pass


class {pascal_name}Update(BaseModel):
    """更新模型"""
    name: Optional[str] = None
    description: Optional[str] = None


class {pascal_name}Response({pascal_name}Base):
    """响应模型"""
    id: int
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True
'''

    def _generate_crud(self, name: str) -> str:
        """生成CRUD操作"""
        pascal_name = ''.join(word.capitalize() for word in name.split('_'))

        return f'''"""
{pascal_name} CRUD Operations
Generated by Leo FastAPI Endpoint Generator
"""

from sqlalchemy.orm import Session
from app.models.{name} import {pascal_name}
from app.schemas.{name} import {pascal_name}Create, {pascal_name}Update


def get_{name}(db: Session, id: int):
    """获取单个记录"""
    return db.query({pascal_name}).filter({pascal_name}.id == id).first()


def get_{name}s(db: Session, skip: int = 0, limit: int = 100):
    """获取列表"""
    return db.query({pascal_name}).offset(skip).limit(limit).all()


def create_{name}(db: Session, item: {pascal_name}Create):
    """创建记录"""
    db_item = {pascal_name}(**item.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item


def update_{name}(db: Session, id: int, item: {pascal_name}Update):
    """更新记录"""
    db_item = get_{name}(db, id)
    if db_item:
        update_data = item.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(db_item, key, value)
        db.commit()
        db.refresh(db_item)
    return db_item


def delete_{name}(db: Session, id: int):
    """删除记录"""
    db_item = get_{name}(db, id)
    if db_item:
        db.delete(db_item)
        db.commit()
        return True
    return False
'''


def main():
    """示例用法"""
    generator = FastAPIEndpointGenerator(output_dir="./output")

    results = generator.generate(
        resource_name='product',
        endpoints=[
            {'method': 'GET', 'path': '/', 'description': '获取产品列表'},
            {'method': 'POST', 'path': '/', 'description': '创建产品'}
        ]
    )

    print("生成完成！")
    for name in results.keys():
        print(f"  - {name}")


if __name__ == '__main__':
    main()
