"""
微信小程序组件生成器 Skill
========================
生成微信小程序自定义组件
"""

from pathlib import Path
from typing import Dict, List, Optional


class MiniprogramComponentGenerator:
    """微信小程序组件生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        component_name: str,
        properties: List[Dict] = None,
        methods: List[str] = None,
        slots: List[str] = None
    ) -> Dict[str, str]:
        """
        生成小程序组件

        Args:
            component_name: 组件名称
            properties: 属性列表
            methods: 方法列表
            slots: 插槽列表

        Returns:
            生成的代码字典
        """
        properties = properties or []
        methods = methods or []
        slots = slots or []

        return {
            'wxml': self._generate_wxml(component_name, slots),
            'wxss': self._generate_wxss(component_name),
            'js': self._generate_js(component_name, properties, methods),
            'json': self._generate_json(component_name)
        }

    def _generate_wxml(self, name: str, slots: List[str]) -> str:
        """生成WXML模板"""
        slot_code = ''
        if slots:
            for slot in slots:
                slot_code += f'\n    <slot name="{slot}"></slot>'

        return f'''<!--
  {name} 组件
  Generated by Leo Miniprogram Component Generator
-->
<view class="{name}-container">
  <view class="{name}-content">
    <slot></slot>{slot_code}
  </view>
</view>
'''

    def _generate_wxss(self, name: str) -> str:
        """生成WXSS样式"""
        return f'''/* {name} 组件样式 */
.{name}-container {{
  display: flex;
  flex-direction: column;
}}

.{name}-content {{
  padding: 20rpx;
}}
'''

    def _generate_js(self, name: str, properties: List[Dict], methods: List[str]) -> str:
        """生成JS逻辑"""
        # 生成properties
        props_code = []
        for prop in properties:
            prop_name = prop.get('name', 'value')
            prop_type = prop.get('type', 'String')
            prop_default = prop.get('default', '""' if prop_type == 'String' else 'null')
            props_code.append(f'''    {prop_name}: {{
      type: {prop_type},
      value: {prop_default}
    }}''')

        props_str = ',\n'.join(props_code) if props_code else ''

        # 生成methods
        methods_code = []
        for method in methods:
            methods_code.append(f'''    {method}() {{
      // TODO: 实现 {method}
    }}''')

        methods_str = ',\n\n'.join(methods_code) if methods_code else ''

        return f'''/**
 * {name} 组件
 * Generated by Leo Miniprogram Component Generator
 */
Component({{
  options: {{
    multipleSlots: true,
    styleIsolation: 'isolated'
  }},

  properties: {{
{props_str}
  }},

  data: {{
    // 组件内部数据
  }},

  lifetimes: {{
    attached() {{
      // 组件实例进入页面节点树时执行
    }},
    detached() {{
      // 组件实例被从页面节点树移除时执行
    }}
  }},

  methods: {{
{methods_str}
  }}
}})
'''

    def _generate_json(self, name: str) -> str:
        """生成JSON配置"""
        return '''{
  "component": true,
  "usingComponents": {}
}
'''

    def save_files(self, name: str, results: Dict[str, str]) -> Dict[str, Path]:
        """保存生成的文件"""
        comp_dir = self.output_dir / 'components' / name
        comp_dir.mkdir(parents=True, exist_ok=True)

        saved = {}
        extensions = {'wxml': '.wxml', 'wxss': '.wxss', 'js': '.js', 'json': '.json'}

        for key, content in results.items():
            ext = extensions.get(key, f'.{key}')
            file_path = comp_dir / f'{name}{ext}'
            file_path.write_text(content, encoding='utf-8')
            saved[key] = file_path

        return saved


def main():
    """示例用法"""
    generator = MiniprogramComponentGenerator(output_dir="./output")

    results = generator.generate(
        component_name='custom-card',
        properties=[
            {'name': 'title', 'type': 'String', 'default': '""'},
            {'name': 'showFooter', 'type': 'Boolean', 'default': 'true'}
        ],
        methods=['onTap', 'onClose'],
        slots=['header', 'footer']
    )

    saved = generator.save_files('custom-card', results)
    print("生成完成！")
    for name, path in saved.items():
        print(f"  {name}: {path}")


if __name__ == '__main__':
    main()
