"""
api_doc_generator_skill - API 文档生成技能

基于 API 路由定义生成 OpenAPI 3.0 规范和 Markdown 文档。
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from leo_skills.core.base_executor import BaseExecutor


class ApiDocGenerator(BaseExecutor):
    """API 文档生成器 - 支持 OpenAPI 3.0 和 Markdown 格式输出"""

    def __init__(self, output_dir: str = ".") -> None:
        self.name = "api_doc_generator_skill"
        self.output_dir = Path(output_dir)

    # ------------------------------------------------------------------
    # BaseExecutor 入口
    # ------------------------------------------------------------------

    def execute(
        self,
        action: str = "generate",
        context: Optional[Dict[str, Any]] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """执行技能

        支持的 action:
            generate - 生成 API 文档（默认）

        参数（通过 context 或 kwargs 传入）:
            api_routes: List[Dict]  - API 路由列表（必填）
            title: str              - 文档标题，默认 "API Documentation"
            version: str            - API 版本号，默认 "1.0.0"
            output_dir: str         - 输出目录（可选，覆盖初始化时的值）
        """
        params: Dict[str, Any] = dict(context or {})
        params.update(kwargs)

        if action == "generate":
            return self._action_generate(params)

        return {"status": "error", "message": f"未知的 action: {action}"}

    # ------------------------------------------------------------------
    # action 实现
    # ------------------------------------------------------------------

    def _action_generate(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """生成 API 文档"""
        api_routes: List[Dict] = params.get("api_routes", [])
        title: str = params.get("title", "API Documentation")
        version: str = params.get("version", "1.0.0")

        if not api_routes:
            return {"status": "error", "message": "api_routes 参数不能为空"}

        # 覆盖输出目录
        if "output_dir" in params:
            self.output_dir = Path(params["output_dir"])

        openapi_doc = self._generate_openapi(api_routes, title, version)
        markdown_doc = self._generate_markdown(api_routes, title, version)

        return {
            "status": "success",
            "action": "generate",
            "data": {
                "openapi": openapi_doc,
                "markdown": markdown_doc,
            },
        }

    # ------------------------------------------------------------------
    # OpenAPI 3.0 生成
    # ------------------------------------------------------------------

    def _generate_openapi(
        self, routes: List[Dict], title: str, version: str
    ) -> str:
        """根据路由列表生成 OpenAPI 3.0 规范 JSON 字符串"""
        paths: Dict[str, Dict] = {}

        for route in routes:
            path = route.get("path", "/")
            method = route.get("method", "GET").lower()
            desc = route.get("description", "")
            params = route.get("parameters", [])
            request_body = route.get("request_body")
            responses = route.get(
                "responses", {"200": {"description": "Success"}}
            )

            if path not in paths:
                paths[path] = {}

            operation: Dict[str, Any] = {
                "summary": desc,
                "responses": responses,
            }

            if params:
                operation["parameters"] = params

            if request_body and method in ("post", "put", "patch"):
                operation["requestBody"] = {
                    "content": {
                        "application/json": {"schema": request_body}
                    }
                }

            paths[path][method] = operation

        openapi_spec = {
            "openapi": "3.0.0",
            "info": {
                "title": title,
                "version": version,
                "description": f"{title} - Generated by Leo API Doc Generator",
            },
            "paths": paths,
        }

        return json.dumps(openapi_spec, indent=2, ensure_ascii=False)

    # ------------------------------------------------------------------
    # Markdown 文档生成
    # ------------------------------------------------------------------

    def _generate_markdown(
        self, routes: List[Dict], title: str, version: str
    ) -> str:
        """根据路由列表生成 Markdown 文档"""
        lines: List[str] = [
            f"# {title}",
            "",
            f"**版本**: {version}",
            "",
            "*Generated by Leo API Doc Generator*",
            "",
            "---",
            "",
            "## 接口列表",
            "",
            "| 方法 | 路径 | 描述 |",
            "|------|------|------|",
        ]

        # 概览表格
        for route in routes:
            method = route.get("method", "GET")
            path = route.get("path", "/")
            desc = route.get("description", "")
            lines.append(f"| {method} | `{path}` | {desc} |")

        lines.extend(["", "---", "", "## 接口详情", ""])

        # 详情区块
        for route in routes:
            method = route.get("method", "GET")
            path = route.get("path", "/")
            desc = route.get("description", "")
            params = route.get("parameters", [])
            request_body = route.get("request_body")

            lines.extend([f"### {method} {path}", "", f"**描述**: {desc}", ""])

            # 参数表
            if params:
                lines.extend(
                    [
                        "**参数**:",
                        "",
                        "| 名称 | 位置 | 类型 | 必填 | 描述 |",
                        "|------|------|------|------|------|",
                    ]
                )
                for param in params:
                    p_name = param.get("name", "")
                    p_in = param.get("in", "query")
                    p_type = param.get("schema", {}).get("type", "string")
                    p_req = "是" if param.get("required") else "否"
                    p_desc = param.get("description", "")
                    lines.append(
                        f"| {p_name} | {p_in} | {p_type} | {p_req} | {p_desc} |"
                    )
                lines.append("")

            # 请求体
            if request_body:
                lines.extend(
                    [
                        "**请求体**:",
                        "",
                        "```json",
                        json.dumps(request_body, indent=2, ensure_ascii=False),
                        "```",
                        "",
                    ]
                )

            # 响应示例
            lines.extend(
                [
                    "**响应示例**:",
                    "",
                    "```json",
                    "{",
                    '  "code": 200,',
                    '  "message": "success",',
                    '  "data": {}',
                    "}",
                    "```",
                    "",
                    "---",
                    "",
                ]
            )

        return "\n".join(lines)


__all__ = ["ApiDocGenerator"]
