"""
API测试生成器 Skill
==================
生成API测试用例
"""

from pathlib import Path
from typing import Dict, List, Optional
import json


class APITestGenerator:
    """API测试生成器"""

    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)

    def generate(
        self,
        api_spec: List[Dict],
        framework: str = "pytest",
        base_url: str = "http://localhost:5000"
    ) -> Dict[str, str]:
        """
        生成API测试

        Args:
            api_spec: API规范列表
            framework: 测试框架 (pytest/unittest)
            base_url: 基础URL

        Returns:
            生成的测试代码字典
        """
        return {
            'test': self._generate_tests(api_spec, framework, base_url),
            'fixtures': self._generate_fixtures(framework, base_url),
            'postman': self._generate_postman_collection(api_spec, base_url)
        }

    def _generate_tests(self, specs: List[Dict], framework: str, base_url: str) -> str:
        """生成测试代码"""
        if framework == 'pytest':
            return self._generate_pytest(specs, base_url)
        else:
            return self._generate_unittest(specs, base_url)

    def _generate_pytest(self, specs: List[Dict], base_url: str) -> str:
        """生成pytest测试"""
        test_cases = []

        for spec in specs:
            method = spec.get('method', 'GET').upper()
            path = spec.get('path', '/')
            desc = spec.get('description', '')
            expected_status = spec.get('expected_status', 200)
            request_body = spec.get('request_body')

            func_name = f"test_{method.lower()}_{path.replace('/', '_').replace('{', '').replace('}', '').strip('_')}"

            if method == 'GET':
                test_cases.append(f'''
def {func_name}(client):
    """{desc}"""
    response = client.get("{path}")
    assert response.status_code == {expected_status}
    assert "data" in response.json() or "error" in response.json()
''')
            elif method == 'POST':
                body_str = json.dumps(request_body or {}, indent=8) if request_body else '{}'
                test_cases.append(f'''
def {func_name}(client):
    """{desc}"""
    payload = {body_str}
    response = client.post("{path}", json=payload)
    assert response.status_code == {expected_status}
''')
            elif method == 'PUT':
                body_str = json.dumps(request_body or {}, indent=8) if request_body else '{}'
                test_cases.append(f'''
def {func_name}(client):
    """{desc}"""
    payload = {body_str}
    response = client.put("{path}", json=payload)
    assert response.status_code == {expected_status}
''')
            elif method == 'DELETE':
                test_cases.append(f'''
def {func_name}(client):
    """{desc}"""
    response = client.delete("{path}")
    assert response.status_code == {expected_status}
''')

        tests_str = '\n'.join(test_cases)

        return f'''"""
API Tests
Generated by Leo API Test Generator
"""

import pytest


class TestAPI:
    """API测试类"""
{tests_str}


# 边界测试
class TestAPIEdgeCases:
    """边界条件测试"""

    def test_invalid_endpoint(self, client):
        """测试无效端点"""
        response = client.get("/invalid/endpoint")
        assert response.status_code == 404

    def test_invalid_method(self, client):
        """测试无效方法"""
        response = client.patch("/api/")
        assert response.status_code in [404, 405]
'''

    def _generate_unittest(self, specs: List[Dict], base_url: str) -> str:
        """生成unittest测试"""
        return f'''"""
API Tests (unittest)
Generated by Leo API Test Generator
"""

import unittest
import requests


class TestAPI(unittest.TestCase):
    """API测试类"""

    BASE_URL = "{base_url}"

    def test_health_check(self):
        """测试健康检查"""
        response = requests.get(f"{{self.BASE_URL}}/health")
        self.assertEqual(response.status_code, 200)


if __name__ == '__main__':
    unittest.main()
'''

    def _generate_fixtures(self, framework: str, base_url: str) -> str:
        """生成测试fixtures"""
        if framework == 'pytest':
            return f'''"""
Pytest Fixtures
Generated by Leo API Test Generator
"""

import pytest
import requests


class APIClient:
    """API测试客户端"""

    def __init__(self, base_url):
        self.base_url = base_url
        self.session = requests.Session()

    def get(self, path, **kwargs):
        return self.session.get(f"{{self.base_url}}{{path}}", **kwargs)

    def post(self, path, **kwargs):
        return self.session.post(f"{{self.base_url}}{{path}}", **kwargs)

    def put(self, path, **kwargs):
        return self.session.put(f"{{self.base_url}}{{path}}", **kwargs)

    def delete(self, path, **kwargs):
        return self.session.delete(f"{{self.base_url}}{{path}}", **kwargs)


@pytest.fixture
def client():
    """API客户端fixture"""
    return APIClient("{base_url}")


@pytest.fixture
def auth_client(client):
    """带认证的API客户端"""
    # TODO: 添加认证逻辑
    client.session.headers.update({{
        "Authorization": "Bearer test-token"
    }})
    return client
'''
        return ''

    def _generate_postman_collection(self, specs: List[Dict], base_url: str) -> str:
        """生成Postman集合"""
        items = []

        for spec in specs:
            method = spec.get('method', 'GET').upper()
            path = spec.get('path', '/')
            desc = spec.get('description', '')
            request_body = spec.get('request_body')

            item = {
                'name': desc or f'{method} {path}',
                'request': {
                    'method': method,
                    'header': [{'key': 'Content-Type', 'value': 'application/json'}],
                    'url': {
                        'raw': f'{base_url}{path}',
                        'host': [base_url.replace('http://', '').replace('https://', '')],
                        'path': path.strip('/').split('/')
                    }
                }
            }

            if request_body and method in ['POST', 'PUT', 'PATCH']:
                item['request']['body'] = {
                    'mode': 'raw',
                    'raw': json.dumps(request_body, indent=2)
                }

            items.append(item)

        collection = {
            'info': {
                'name': 'API Tests',
                'description': 'Generated by Leo API Test Generator',
                'schema': 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
            },
            'item': items
        }

        return json.dumps(collection, indent=2, ensure_ascii=False)


def main():
    """示例用法"""
    generator = APITestGenerator(output_dir="./output")

    api_spec = [
        {'method': 'GET', 'path': '/api/users', 'description': '获取用户列表'},
        {'method': 'POST', 'path': '/api/users', 'description': '创建用户', 'request_body': {'name': 'test'}},
        {'method': 'GET', 'path': '/api/users/{id}', 'description': '获取用户详情'},
        {'method': 'DELETE', 'path': '/api/users/{id}', 'description': '删除用户'}
    ]

    results = generator.generate(
        api_spec=api_spec,
        framework='pytest',
        base_url='http://localhost:5000'
    )

    print("生成完成！")
    for name in results.keys():
        print(f"  - {name}")


if __name__ == '__main__':
    main()
