"""
css_layout_generator_skill

CSS布局生成技能 - 生成响应式CSS布局代码，支持Grid、Flex、圣杯、侧边栏、仪表盘等布局类型。
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

from leo_skills.core.base_executor import BaseExecutor


class CSSLayoutGenerator(BaseExecutor):
    """CSS布局生成器

    支持的布局类型：
    - grid: CSS Grid 栅格布局
    - flex: Flexbox 弹性布局
    - holy-grail: 圣杯布局（经典三列）
    - sidebar: 侧边栏布局
    - dashboard: 仪表盘布局
    """

    def __init__(self, output_dir: str = ".") -> None:
        self.name = "css_layout_generator_skill"
        self.output_dir = Path(output_dir)

    # ------------------------------------------------------------------ #
    #  BaseExecutor 接口
    # ------------------------------------------------------------------ #

    def execute(
        self,
        action: str = "generate",
        context: Optional[Dict[str, Any]] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """执行技能入口

        Args:
            action: 动作类型，默认 "generate"
            context: 上下文参数（可包含 layout_type / breakpoints / options）
            **kwargs: 其他关键字参数
        """
        params: Dict[str, Any] = dict(context or {})
        params.update(kwargs)

        layout_type = params.get("layout_type", "flex")
        breakpoints = params.get("breakpoints")
        options = params.get("options", {})

        result = self.generate(
            layout_type=layout_type,
            breakpoints=breakpoints,
            options=options,
        )
        return {"status": "success", "action": action, "data": result}

    # ------------------------------------------------------------------ #
    #  核心生成逻辑
    # ------------------------------------------------------------------ #

    def generate(
        self,
        layout_type: str,
        breakpoints: Optional[Dict[str, int]] = None,
        options: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, str]:
        """生成CSS布局

        Args:
            layout_type: 布局类型 (grid/flex/holy-grail/sidebar/dashboard)
            breakpoints: 响应式断点配置
            options: 其他选项（如列数、间距、侧边栏宽度等）

        Returns:
            {'css': '...', 'tailwind': '...'} 生成的代码字典
        """
        breakpoints = breakpoints or {"sm": 640, "md": 768, "lg": 1024, "xl": 1280}
        options = options or {}

        generators = {
            "grid": self._generate_grid_layout,
            "flex": self._generate_flex_layout,
            "holy-grail": self._generate_holy_grail,
            "sidebar": self._generate_sidebar_layout,
            "dashboard": self._generate_dashboard_layout,
        }

        generator = generators.get(layout_type, self._generate_flex_layout)
        css = generator(breakpoints, options)
        tailwind = self._generate_tailwind_classes(layout_type, options)

        return {"css": css, "tailwind": tailwind}

    # ------------------------------------------------------------------ #
    #  各布局类型的 CSS 生成
    # ------------------------------------------------------------------ #

    def _generate_grid_layout(self, breakpoints: Dict[str, int], options: Dict[str, Any]) -> str:
        """生成 CSS Grid 栅格布局"""
        cols = options.get("columns", 12)
        gap = options.get("gap", "1rem")

        return f"""/* Grid Layout - Generated by Leo CSS Layout Generator */
.grid-container {{
  display: grid;
  grid-template-columns: repeat({cols}, 1fr);
  gap: {gap};
}}

/* 响应式列 */
@media (max-width: {breakpoints.get("md", 768)}px) {{
  .grid-container {{
    grid-template-columns: repeat(6, 1fr);
  }}
}}

@media (max-width: {breakpoints.get("sm", 640)}px) {{
  .grid-container {{
    grid-template-columns: 1fr;
  }}
}}

/* 列跨度 */
.col-span-1 {{ grid-column: span 1; }}
.col-span-2 {{ grid-column: span 2; }}
.col-span-3 {{ grid-column: span 3; }}
.col-span-4 {{ grid-column: span 4; }}
.col-span-6 {{ grid-column: span 6; }}
.col-span-12 {{ grid-column: span 12; }}
"""

    def _generate_flex_layout(self, breakpoints: Dict[str, int], options: Dict[str, Any]) -> str:
        """生成 Flexbox 弹性布局"""
        return f"""/* Flex Layout - Generated by Leo CSS Layout Generator */
.flex-container {{
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
}}

.flex-row {{
  display: flex;
  flex-direction: row;
}}

.flex-col {{
  display: flex;
  flex-direction: column;
}}

.flex-center {{
  display: flex;
  justify-content: center;
  align-items: center;
}}

.flex-between {{
  display: flex;
  justify-content: space-between;
  align-items: center;
}}

.flex-1 {{ flex: 1; }}
.flex-auto {{ flex: auto; }}
.flex-none {{ flex: none; }}

/* 响应式 */
@media (max-width: {breakpoints.get("md", 768)}px) {{
  .flex-container {{
    flex-direction: column;
  }}
}}
"""

    def _generate_holy_grail(self, breakpoints: Dict[str, int], options: Dict[str, Any]) -> str:
        """生成圣杯布局（经典三列：头部 + 导航/主内容/侧边 + 底部）"""
        return f"""/* Holy Grail Layout - Generated by Leo CSS Layout Generator */
.holy-grail {{
  display: grid;
  grid-template-areas:
    "header header header"
    "nav main aside"
    "footer footer footer";
  grid-template-columns: 200px 1fr 200px;
  grid-template-rows: auto 1fr auto;
  min-height: 100vh;
}}

.holy-grail-header {{ grid-area: header; }}
.holy-grail-nav {{ grid-area: nav; }}
.holy-grail-main {{ grid-area: main; }}
.holy-grail-aside {{ grid-area: aside; }}
.holy-grail-footer {{ grid-area: footer; }}

@media (max-width: {breakpoints.get("md", 768)}px) {{
  .holy-grail {{
    grid-template-areas:
      "header"
      "nav"
      "main"
      "aside"
      "footer";
    grid-template-columns: 1fr;
  }}
}}
"""

    def _generate_sidebar_layout(self, breakpoints: Dict[str, int], options: Dict[str, Any]) -> str:
        """生成侧边栏布局"""
        sidebar_width = options.get("sidebar_width", "250px")

        return f"""/* Sidebar Layout - Generated by Leo CSS Layout Generator */
.sidebar-layout {{
  display: flex;
  min-height: 100vh;
}}

.sidebar {{
  width: {sidebar_width};
  flex-shrink: 0;
  background: #f5f5f5;
}}

.main-content {{
  flex: 1;
  padding: 20px;
}}

@media (max-width: {breakpoints.get("md", 768)}px) {{
  .sidebar-layout {{
    flex-direction: column;
  }}
  .sidebar {{
    width: 100%;
  }}
}}
"""

    def _generate_dashboard_layout(self, breakpoints: Dict[str, int], options: Dict[str, Any]) -> str:
        """生成仪表盘布局"""
        return f"""/* Dashboard Layout - Generated by Leo CSS Layout Generator */
.dashboard {{
  display: grid;
  grid-template-areas:
    "sidebar header"
    "sidebar main";
  grid-template-columns: 250px 1fr;
  grid-template-rows: 60px 1fr;
  min-height: 100vh;
}}

.dashboard-sidebar {{
  grid-area: sidebar;
  background: #1a1a2e;
  color: white;
}}

.dashboard-header {{
  grid-area: header;
  background: white;
  border-bottom: 1px solid #eee;
  padding: 0 20px;
  display: flex;
  align-items: center;
}}

.dashboard-main {{
  grid-area: main;
  padding: 20px;
  background: #f5f7fa;
  overflow-y: auto;
}}

@media (max-width: {breakpoints.get("lg", 1024)}px) {{
  .dashboard {{
    grid-template-areas:
      "header"
      "main";
    grid-template-columns: 1fr;
    grid-template-rows: 60px 1fr;
  }}
  .dashboard-sidebar {{
    display: none;
  }}
}}
"""

    # ------------------------------------------------------------------ #
    #  Tailwind CSS 类生成
    # ------------------------------------------------------------------ #

    def _generate_tailwind_classes(self, layout_type: str, options: Dict[str, Any]) -> str:
        """生成对应布局的 Tailwind CSS 类名"""
        templates = {
            "grid": "grid grid-cols-12 gap-4 md:grid-cols-6 sm:grid-cols-1",
            "flex": "flex flex-wrap gap-4 md:flex-col",
            "holy-grail": "grid grid-rows-[auto_1fr_auto] min-h-screen",
            "sidebar": "flex min-h-screen md:flex-col",
            "dashboard": "grid grid-cols-[250px_1fr] grid-rows-[60px_1fr] min-h-screen lg:grid-cols-1",
        }
        return templates.get(layout_type, templates["flex"])


__all__ = ["CSSLayoutGenerator"]
