"""
vue_component_generator_skill

Vue3组件生成技能 - 生成 Vue3 组件（Composition API + TypeScript），含类型定义和测试。
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from leo_skills.core.base_executor import BaseExecutor


class VueComponentGenerator(BaseExecutor):
    """Vue3组件生成器

    生成内容包括：
    - Vue 单文件组件（.vue）：script setup + scoped SCSS
    - TypeScript 类型定义（.types.ts）：Props 和 Emits 接口
    - 单元测试（.spec.ts）：Vitest + Vue Test Utils
    - 导出文件（index.ts）
    """

    def __init__(self, output_dir: str = ".", typescript: bool = True) -> None:
        self.name = "vue_component_generator_skill"
        self.output_dir = Path(output_dir)
        self.typescript = typescript

    # ------------------------------------------------------------------ #
    #  BaseExecutor 接口
    # ------------------------------------------------------------------ #

    def execute(
        self,
        action: str = "generate",
        context: Optional[Dict[str, Any]] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """执行技能入口

        Args:
            action: 动作类型，默认 "generate"
            context: 上下文参数
            **kwargs: 其他关键字参数
        """
        params: Dict[str, Any] = dict(context or {})
        params.update(kwargs)

        component_name = params.get("component_name", "MyComponent")
        props = params.get("props", [])
        emits = params.get("emits", [])
        slots = params.get("slots", [])
        features = params.get("features", [])
        save = params.get("save", False)

        if "typescript" in params:
            self.typescript = params["typescript"]

        result = self.generate(
            component_name=component_name,
            props=props,
            emits=emits,
            slots=slots,
            features=features,
        )

        if save:
            saved = self.save_files(component_name, result)
            return {
                "status": "success",
                "action": action,
                "data": result,
                "saved_files": {k: str(v) for k, v in saved.items()},
            }

        return {"status": "success", "action": action, "data": result}

    # ------------------------------------------------------------------ #
    #  核心生成逻辑
    # ------------------------------------------------------------------ #

    def generate(
        self,
        component_name: str,
        props: Optional[List[Dict[str, Any]]] = None,
        emits: Optional[List[str]] = None,
        slots: Optional[List[str]] = None,
        features: Optional[List[str]] = None,
    ) -> Dict[str, str]:
        """生成Vue3组件

        Args:
            component_name: 组件名称（PascalCase）
            props: 属性定义列表
            emits: 事件列表
            slots: 插槽列表
            features: 特性列表（如 'loading', 'computed', 'watch', 'lifecycle'）

        Returns:
            生成的代码字典
        """
        props = props or []
        emits = emits or []
        slots = slots or []
        features = features or []

        results: Dict[str, str] = {}

        # Vue 单文件组件
        results["vue"] = self._generate_vue_component(
            component_name, props, emits, slots, features
        )

        # TypeScript 类型定义
        if self.typescript:
            results["types"] = self._generate_types(component_name, props, emits)

        # 单元测试
        results["test"] = self._generate_test(component_name, props)

        return results

    # ------------------------------------------------------------------ #
    #  Vue 单文件组件生成
    # ------------------------------------------------------------------ #

    def _generate_vue_component(
        self,
        name: str,
        props: List[Dict[str, Any]],
        emits: List[str],
        slots: List[str],
        features: List[str],
    ) -> str:
        """生成 Vue3 单文件组件（template + script setup + scoped style）"""
        template = self._generate_template(name, props, slots, features)
        script_content = self._generate_script_content(name, props, emits, features)
        style = self._generate_style(name, features)

        ext = "ts" if self.typescript else "js"

        return f"""<template>
{template}
</template>

<script setup lang="{ext}">
/**
 * {name} 组件
 * Generated by Leo Vue Component Generator
 */
{script_content}
</script>

<style scoped lang="scss">
{style}
</style>
"""

    # ------------------------------------------------------------------ #
    #  模板生成
    # ------------------------------------------------------------------ #

    def _generate_template(
        self,
        name: str,
        props: List[Dict[str, Any]],
        slots: List[str],
        features: List[str],
    ) -> str:
        """生成 template 部分"""
        kebab_name = self._to_kebab_case(name)

        content = f'  <div class="{kebab_name}">'

        # Loading 状态
        if "loading" in features:
            content += """
    <div v-if="loading" class="loading-wrapper">
      <span class="loading-spinner"></span>
    </div>
    <template v-else>"""

        # 插槽
        if slots:
            for slot in slots:
                if slot == "default":
                    content += "\n      <slot></slot>"
                else:
                    content += f'\n      <slot name="{slot}"></slot>'
        else:
            content += "\n      <!-- 组件内容 -->"

        if "loading" in features:
            content += "\n    </template>"

        content += "\n  </div>"
        return content

    # ------------------------------------------------------------------ #
    #  脚本生成
    # ------------------------------------------------------------------ #

    def _generate_script_content(
        self,
        name: str,
        props: List[Dict[str, Any]],
        emits: List[str],
        features: List[str],
    ) -> str:
        """生成 script setup 内容"""
        lines = []

        # Vue 导入
        vue_imports = ["ref"]
        if "computed" in features:
            vue_imports.append("computed")
        if "watch" in features:
            vue_imports.append("watch")
        if "lifecycle" in features:
            vue_imports.extend(["onMounted", "onUnmounted"])

        lines.append(f"import {{ {', '.join(vue_imports)} }} from 'vue'")
        lines.append("")

        # Props 定义
        if props:
            lines.append(self._generate_props_definition(props))
            lines.append("")

        # Emits 定义
        if emits:
            emits_types = self._generate_emits_types(emits)
            lines.append(f"const emit = defineEmits<{{{emits_types}}}>()")
            lines.append("")

        # 响应式状态
        if "loading" in features:
            lines.append("const loading = ref(false)")

        # 生命周期钩子
        if "lifecycle" in features:
            lines.append("")
            lines.append("onMounted(() => {")
            lines.append("  // 组件挂载后执行")
            lines.append("})")
            lines.append("")
            lines.append("onUnmounted(() => {")
            lines.append("  // 组件卸载前执行")
            lines.append("})")

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    #  Props 定义生成
    # ------------------------------------------------------------------ #

    def _generate_props_definition(self, props: List[Dict[str, Any]]) -> str:
        """生成 defineProps 的 TypeScript 接口"""
        if not props:
            return ""

        lines = []
        for prop in props:
            name = prop["name"]
            ptype = prop.get("type", "string")
            required = prop.get("required", False)
            ts_type = self._map_ts_type(ptype)

            if required:
                lines.append(f"  {name}: {ts_type}")
            else:
                lines.append(f"  {name}?: {ts_type}")

        return "interface Props {\n" + "\n".join(lines) + "\n}\n\nconst props = defineProps<Props>()"

    # ------------------------------------------------------------------ #
    #  Emits 类型生成
    # ------------------------------------------------------------------ #

    @staticmethod
    def _generate_emits_types(emits: List[str]) -> str:
        """生成 defineEmits 的类型签名"""
        lines = []
        for emit in emits:
            lines.append(f"  (e: '{emit}', value: any): void")
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    #  样式生成
    # ------------------------------------------------------------------ #

    def _generate_style(self, name: str, features: List[str]) -> str:
        """生成 scoped SCSS 样式"""
        kebab_name = self._to_kebab_case(name)

        style = f""".{kebab_name} {{
  position: relative;
}}"""

        if "loading" in features:
            style += """

.loading-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100px;
}

.loading-spinner {
  width: 24px;
  height: 24px;
  border: 2px solid #f3f3f3;
  border-top: 2px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}"""

        return style

    # ------------------------------------------------------------------ #
    #  TypeScript 类型定义文件
    # ------------------------------------------------------------------ #

    def _generate_types(
        self,
        name: str,
        props: List[Dict[str, Any]],
        emits: List[str],
    ) -> str:
        """生成独立的 TypeScript 类型定义文件"""
        lines = [f"// {name} 类型定义", ""]

        # Props 接口
        if props:
            lines.append(f"export interface {name}Props {{")
            for prop in props:
                pname = prop["name"]
                ptype = self._map_ts_type(prop.get("type", "string"))
                required = prop.get("required", False)
                optional = "" if required else "?"
                lines.append(f"  {pname}{optional}: {ptype}")
            lines.append("}")
            lines.append("")

        # Emits 接口
        if emits:
            lines.append(f"export interface {name}Emits {{")
            for emit in emits:
                lines.append(f"  (e: '{emit}', value: any): void")
            lines.append("}")

        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    #  测试文件
    # ------------------------------------------------------------------ #

    def _generate_test(self, name: str, props: List[Dict[str, Any]]) -> str:
        """生成 Vitest + Vue Test Utils 测试文件"""
        kebab_name = self._to_kebab_case(name)

        # 生成 props mock 数据
        props_mock = "{"
        for prop in props:
            pname = prop["name"]
            ptype = prop.get("type", "string")
            if ptype == "string":
                props_mock += f"\n      {pname}: 'test',"
            elif ptype == "number":
                props_mock += f"\n      {pname}: 1,"
            elif ptype == "boolean":
                props_mock += f"\n      {pname}: true,"
            elif ptype == "array":
                props_mock += f"\n      {pname}: [],"
            else:
                props_mock += f"\n      {pname}: {{}},"
        props_mock += "\n    }" if props else "{}"

        return f"""import {{ describe, it, expect }} from 'vitest'
import {{ mount }} from '@vue/test-utils'
import {name} from './{name}.vue'

describe('{name}', () => {{
  it('renders properly', () => {{
    const wrapper = mount({name}, {{
      props: {props_mock}
    }})
    expect(wrapper.exists()).toBe(true)
  }})

  it('has correct class name', () => {{
    const wrapper = mount({name})
    expect(wrapper.classes()).toContain('{kebab_name}')
  }})
}})
"""

    # ------------------------------------------------------------------ #
    #  文件保存
    # ------------------------------------------------------------------ #

    def save_files(self, component_name: str, results: Dict[str, str]) -> Dict[str, Path]:
        """将生成的组件代码保存到文件

        Args:
            component_name: 组件名称
            results: generate() 返回的代码字典

        Returns:
            {文件类型: 文件路径} 的字典
        """
        comp_dir = self.output_dir / "components" / component_name
        comp_dir.mkdir(parents=True, exist_ok=True)

        saved: Dict[str, Path] = {}

        # Vue 组件
        vue_path = comp_dir / f"{component_name}.vue"
        vue_path.write_text(results["vue"], encoding="utf-8")
        saved["vue"] = vue_path

        # 类型定义
        if "types" in results:
            types_path = comp_dir / f"{component_name}.types.ts"
            types_path.write_text(results["types"], encoding="utf-8")
            saved["types"] = types_path

        # 测试文件
        test_path = comp_dir / f"{component_name}.spec.ts"
        test_path.write_text(results["test"], encoding="utf-8")
        saved["test"] = test_path

        # 导出文件
        index_content = f"export {{ default as {component_name} }} from './{component_name}.vue'\n"
        if "types" in results:
            index_content += f"export * from './{component_name}.types'\n"
        index_path = comp_dir / "index.ts"
        index_path.write_text(index_content, encoding="utf-8")
        saved["index"] = index_path

        return saved

    # ------------------------------------------------------------------ #
    #  工具方法
    # ------------------------------------------------------------------ #

    @staticmethod
    def _map_ts_type(ptype: str) -> str:
        """将简写类型映射为 TypeScript 类型"""
        type_map = {
            "string": "string",
            "number": "number",
            "boolean": "boolean",
            "array": "any[]",
            "object": "Record<string, any>",
            "function": "(...args: any[]) => any",
            "date": "Date",
        }
        return type_map.get(ptype.lower(), "any")

    @staticmethod
    def _to_kebab_case(name: str) -> str:
        """将 PascalCase 转换为 kebab-case"""
        s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1-\2", name)
        return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s1).lower()


__all__ = ["VueComponentGenerator"]
